### ISSUE TITLE
All commands fail after install

### ISSUE THREAD

**Issue by Permiek** [ibmdb/vscode-extension#1]
OS: Windows Server 2016 Standard Version 1607 OS build 14393.2791
VScode: 1.36.1

Any attempt to use commands using command pallette result in:
command 'extension.Db2ManageConnProfiles' not found

No problems or other errors reported.

I have tried re-install and reload several times.

**Comment by akhilravuri1** [comment]
Hi @Permiek 

Since the electron version of vscode has been changed our extension is not working on vscode 1.36 and later.
we are going to release the new version of Db2Connect very soon in that electron version is fixed.

Thanks,
Akhil

**Comment by Permiek** [comment]
Cool, thanks

**Comment by akhilravuri1** [comment]
Hi @Permiek 

A new version of db2connect vscode extension is available in the marketplace you can update the extension and use it.

Thanks,
Akhil

**Comment by Permiek** [comment]
Cool, thanks
