### ISSUE TITLE
Extensions not working

### ISSUE THREAD

**Issue by mloss2423** [ibmdb/vscode-extension#10]
I have been having issues with the extension recently. I want to create a new connection but i keep getting this error.

command 'extension.Db2ManageConnProfiles' not found

**Comment by akhilravuri1** [comment]
Hi @mloss2423 

Are you using vscode version 1.42?

**Comment by mloss2423** [comment]
I have 1.42 now. I'm running this on Windows. I tried again and get this message.

"Failed to rebuild native modules, please reach out to our git page for help"

**Comment by akhilravuri1** [comment]
Hi @mloss2423 
sorry for the late reply.

Uninstall the extension and go to  extension folder in .vscode (C:\Users\rakhil\.vscode\extensions) delete ibm.db2connect-win-1.1.0 floder and try to install the extension. 
After installation when you click Db2: Connect it tries to build native modules so at that time click the new terminal and go to the Output tab and select Db2Connect in that dropdown.
![image](https://user-images.githubusercontent.com/32290825/74148557-b6a82900-4c2b-11ea-9751-cd8921b7cb46.png)

If you are facing issues please paste that log.

**Comment by akhilravuri1** [comment]
Hi @mloss2423 

This is can be because of proxy issue also please allow your nodes connections through windows firewall. https://docs.profoundlogic.com/display/PUI/Allowing+Connections+in+Windows+Firewall

Thanks,
Akhil

**Comment by mloss2423** [comment]
Here is the log..

[2/10/2020 9:41:24 AM] Proceeding to rebuild native modules
[2/10/2020 9:41:24 AM] Cleaning up the current ibm_db
Running npm install,ibm_db in
c:\Users\michael.lossing\.vscode\extensions\ibm.db2connect-win-1.1.0...
'npm' is not recognized as an internal or external command,
operable program or batch file.
[2/10/2020 9:41:27 AM] ibm_db installation failed with code: 1
Error: Failed to execute command "npm" with  arguments "install,
ibm_db" return code 1


Thank you,

*Michael Lossing*
*EOA Lab Operations - **Business Systems Analyst *
*Essilor of America*

*Cell: (248)-420-7525*
*Work: (214)-496-4262*
*Email: michael.lossing@essilorusa.com <michael.lossing@essilorusa.com>*

**Comment by mloss2423** [comment]
This is the log it is showing.

Here is the log..

[2/10/2020 9:41:24 AM] Proceeding to rebuild native modules
[2/10/2020 9:41:24 AM] Cleaning up the current ibm_db
Running npm install,ibm_db in c:\Users\michael.lossing\.vscode\extensions\ibm.db2connect-win-1.1.0...
'npm' is not recognized as an internal or external command,
operable program or batch file.
[2/10/2020 9:41:27 AM] ibm_db installation failed with code: 1
Error: Failed to execute command "npm" with  arguments "install, ibm_db" return code 1

**Comment by bimalkjha** [comment]
@mloss2423 Please install node.js v12.x in your system to resolve this issue. npm comes with node.js installation. The error "'npm' is not recognized as an internal or external command," tells that vscode is unable to find any node.js installed in the system. Thanks.
