### ISSUE TITLE
command 'extension.Db2ManageConnProfiles' not found

### ISSUE THREAD

**Issue by SarahZhou2018** [ibmdb/vscode-extension#12]
Hi,

I have this issue with mac version :(
command 'extension.Db2ManageConnProfiles' not found
Failed to rebuild native modules, please reach out to our git page for help

Version: 1.42.1
Date: 2020-02-11T14:44:27.652Z
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by akhilravuri1** [comment]
Hi @SarahZhou2018 
Is npm and node.js installed in your system?

If yes, please uninstall the extension and close the vscode and install the extension.

After installing when you select any Db2 Connect option it shows a notification that "BUILDING NATIVE MODULES"

while installing go to the OUTPUT tab in the terminal and select DB2CONNECT extension in that and copy-paste the log.

![image](https://user-images.githubusercontent.com/32290825/75512880-deafce80-5a18-11ea-83c1-15e222588c51.png)

Thanks,
Akhil

**Comment by SarahZhou2018** [comment]
hi,
thanks for the response! 
I have followed the steps, but..
help

![Screen Shot 2020-02-28 at 12 36 47 AM](https://user-images.githubusercontent.com/45517534/75513515-12f8a000-59c3-11ea-9eea-bb52b74c87f6.png)

**Comment by marciomorgado** [comment]
Hi, I'm getting the same problem, did the steps, but still getting error:
[3/6/2020 5:46:26 PM] ibm_db installation failed with code: 1
Error: Failed to execute command "npm" with  arguments "install, ibm_db" return code 1
Log:
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'ibm_db'
1 verbose cli ]
2 info using npm@6.12.1
3 info using node@v12.13.1
4 verbose npm-session 513e13800416f2ef
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 silly fetchPackageMetaData error for ibm_db@git+https://github.com/ibmdb/node-ibm_db.git#vscode Error while executing:
7 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData
7 silly fetchPackageMetaData spawn git ENOENT
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 162ms
10 verbose stack Error: spawn git ENOENT
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
10 verbose stack     at onErrorNT (internal/child_process.js:456:16)
10 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:80:21)
11 verbose cwd c:\Users\mm612452\.vscode\extensions\ibm.db2connect-win-1.1.0
12 verbose Windows_NT 10.0.18362
13 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "ibm_db"
14 verbose node v12.13.1
15 verbose npm  v6.12.1
16 error code ENOENT
17 error syscall spawn git
18 error path git
19 error errno ENOENT
20 error enoent Error while executing:
20 error enoent undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
20 error enoent
20 error enoent
20 error enoent spawn git ENOENT
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ 1, true ]

**Comment by akhilravuri1** [comment]
Hi @marciomorgado 
sorry for the late reply.

Are you facing the issue now?

Thanks,
Akhil

**Comment by marciomorgado** [comment]
Thanks Akhil, it was fixed.
Márcio Morgado


Em qua., 6 de mai. de 2020 às 03:34, Akhil Ravuri <notifications@github.com>
escreveu:
