### ISSUE TITLE
Failed to rebuild native modules, please reach out to our git page for help...

### ISSUE THREAD

**Issue by pdbossman** [ibmdb/vscode-extension#13]
The installation completes.  I had to uninstall and re-install xcode on my mac, as it wasn't finding the xcode version for some reason.

Now when I perform Db2:Manage Connection Profiles - I get the following:

```
****************************************
You are downloading a package which includes the Node.js module for IBM DB2/Informix.  The module is licensed under the Apache License 2.0. The package also includes IBM ODBC and CLI Driver from IBM, which is automatically downloaded as the node module is installed on your system/device. The license agreement to the IBM ODBC and CLI Driver is available in undefined   Check for additional dependencies, which may come with their own license agreement(s). Your use of the components of the package and dependencies constitutes your acceptance of their respective license agreements. If you do not accept the terms of any license agreement(s), then delete the relevant component(s) from your device.
****************************************
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...
  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  SOLINK_MODULE(target) Release/odbc_bindings.node
npm
 WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN Db2connect@1.1.0 No repository field.
npm 
WARN Db2connect@1.1.0 No license field.

+ ibm_db@2.6.3
added 1 package from 2 contributors and audited 518 packages in 15.928s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details
[3/10/2020 1:18:26 PM] Finished successfully installing the component
Error: The module '/Users/bossmanus.ibm.com/.vscode/extensions/ibm.db2connect-1.1.0/node_modules/ibm_db/build/Release/odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 73. This version of Node.js requires
NODE_MODULE_VERSION 75. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
```

I have cd cd /Users/bossmanus.ibm.com/.vscode/extensions/ibm.db2connect-1.1.0/node_modules/ibm_db/build/Release/
then npm rebuild and npm install.  I still get this error.

**Comment by bimalkjha** [comment]
@pdbossman In your vscode window, click on Help -> About and share the screenshot as below:
![image](https://user-images.githubusercontent.com/11818648/76386405-7226bf00-638a-11ea-87d8-c1877879724d.png) 
We need to know your vscode version, electron version and node.js version to assist you. Thanks.

**Comment by rrmanthonyc** [comment]
Hello,

I'm having the same issue that @pdbossman is having. Here are the details of my VS Code installation.

Version: 1.43.0
Commit: 78a4c91400152c0f27ba4d363eb56d2835f9903a
Date: 2020-03-09T19:34:44.548Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

**Comment by akhilravuri1** [comment]
Hi @rrmanthonyc 

This issue is related to major electron release. Our node ibm_db driver has to be compiled with the latest electron version.

We will fix this as fast as possible.

Thanks,
Akhil

**Comment by rrmanthonyc** [comment]
Hello @akhilravuri1,

Sounds good. Thank you!

**Comment by akhilravuri1** [comment]
Hi @rrmanthonyc 

we have updated our node_ibm_db driver please reinstall the extension. If reinstall is not working please delete the ibmdb folder in .vscode/extensions and install it again.

Thanks,
Akhil

**Comment by GutterBeats** [comment]
Hello @akhilravuri1,

It looks like it is working now.

Thank you!

**Comment by pdbossman** [comment]
I've downloaded the new version and I am past the issue - thank you!  (And thank you @akhilravuri1 for moving problem determination forward)
