### ISSUE TITLE
Attempt to test connection to Db2 for z/OS raises license issue

### ISSUE THREAD

**Issue by pdbossman** [ibmdb/vscode-extension#14]
`Test failed: Error: [IBM][CLI Driver] SQL1598N  An attempt to connect to the database server failed because of a licensing problem.  SQLSTATE=42968`

I did not see any recommendations/pre-reqs related to license files.  What pre-reqs and/or actions are required here?

**Comment by akhilravuri1** [comment]
Hi @pdbossman 

As you said you are connecting to Db2 for z/OS which requires a license. Can you please verify that do you have a z/os license file in the clidriver/license folder.

Thanks,
Akhil

**Comment by pdbossman** [comment]
I followed the install instructions to install the extension, that is it.  Where are the instructions talking about this?

**Comment by bimalkjha** [comment]
@pdbossman 
**For z/OS and iSeries Connectivity**
For connectivity against DB2 for LUW or Informix Server using node-ibm_db, no license file is required. However, if you want to use db2connect vscode extension against DB2 for z/OS or DB2 for i(AS400) Servers, you must have db2connect license of version 11.1 if server is not db2connectactivated to accept unlimited number of client connection. You can buy db2connect license from IBM. The connectivity can be enabled either on server using db2connectactivate utility or on client using client side license file. Please check with your DBA if they can configure server to accept connectivity from your system using db2connect. If you have client side license file, just copy it under `.../db2connect/node_modules/ibm_db/installer/clidriver/license` folder to be effective.

To know more about license and purchasing cost, please contact [IBM Customer Support](https://www.ibm.com/support/customer/zz/en/selectcountrylang.html).

@akhilravuri1 You may update the vscode extension doc mentioned above same as its is documented [here](https://github.com/ibmdb/node-ibm_db#for-zos-and-iseries-connectivity). Thanks.

**Comment by akhilravuri1** [comment]
Thanks, @bimalkjha for the information.

I have updated the readme file.
