### ISSUE TITLE
DB2 Manage Connection profiles

### ISSUE THREAD

**Issue by choco97129** [ibmdb/vscode-extension#15]
Hi,

I have an issue with DB2 extension.
This message appear : command 'extension.Db2ManageConnProfiles' not found

I have the last version of visual studio code

Can you helpme please

**Comment by akhilravuri1** [comment]
Hi @choco97129 

On which platform are you installing?
Please confirm node.js and npm are installed in your system or not?

If yes open vscode and open a new terminal in vscode and run
```
node -v 
npm -v
```
Take a screenshot and share that.

Thanks,
Akhil

**Comment by choco97129** [comment]
Hi Akhil,

I use Windows Plateform fort Visual Studio Code. I installed The extension for windows.

Please find below results of each command

 [cid:4BFAEF74-C8EF-4BC5-91CC-22EC074F6ACC-L0-001]

Thank you for tour help

Best Regards,

Envoyé de mon iPhone

Le 22 avr. 2020 à 09:22, Akhil Ravuri <notifications@github.com> a écrit :

﻿

Hi @choco97129<https://github.com/choco97129>

On which platform are you installing?
Please confirm node.js and npm are installed in your system or not?

If yes open vscode and open a new terminal in vscode and run

node -v
npm -v


Take a screenshot and share that.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @choco97129 

I don't see any file attached to the comment.

Can you please upload it again?

Thanks,
Akhil

**Comment by choco97129** [comment]
Hi Akhil,

Sorry, i replied from my email.
I uploaded again  the file.

Please let me know if it is ok

Thanks
![Version_Npm _Node](https://user-images.githubusercontent.com/6282250/80288934-adfbc500-873b-11ea-96f5-2817c1d9fec8.jpg)

**Comment by akhilravuri1** [comment]
Hi @choco97129 

sorry for the late reply.

Please uninstall the extension and delete the ibm.db2connect-win-1.1.0 folder in .vscode/extensions path.

Thanks,
Akhil

**Comment by choco97129** [comment]
Hi

Sorry for my late.
I have the same issue

Regards

Envoyé de mon iPhone

Le 6 mai 2020 à 08:32, Akhil Ravuri <notifications@github.com> a écrit :

﻿

Hi @choco97129<https://github.com/choco97129>

sorry for the late reply.

Please uninstall the extension and delete the ibm.db2connect-win-1.1.0 folder in .vscode/extensions path.

Thanks,
Akhil

**Comment by spufidoo** [comment]
I too have the same issue. Deleting the ibm.db2connect-win-1.1.0 folder in the .vscode/extensions path doesn't make any difference. The new extension has a folder name of Db2Connect. Should I place my license folder in there somewhere?
