### ISSUE TITLE
Doc link is defunct

### ISSUE THREAD

**Issue by data-henrik** [ibmdb/vscode-extension#18]
I am using db2connect extension for Linux. There is a link to usage documentation in the description: https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/VS_Code_extension_for_Db2Connect?lang=en

It leads to a general overview page, but not to any documentation. Why not maintain the documentation here in a Wiki to this repo?

**Comment by akhilravuri1** [comment]
Thanks for the input. We take this in our next release.

-Akhil

**Comment by shilumathai** [comment]
IBM developer works got migrated to a new link. Please use the below link
https://community.ibm.com/community/user/hybriddatamanagement/blogs/sujan-ghosh1/2020/07/14/vs-code-extension-for-db2connect?CommunityKey=f2e5dc34-896d-4e8e-9678-724907c4b9f5&tab=recentcommunityblogsdashboard

we will update the readme with this link in the new release coming up soon with lot of new features

**Comment by akhilravuri1** [comment]
> IBM developer works got migrated to a new link. Please use the below link
> https://community.ibm.com/community/user/hybriddatamanagement/blogs/sujan-ghosh1/2020/07/14/vs-code-extension-for-db2connect?CommunityKey=f2e5dc34-896d-4e8e-9678-724907c4b9f5&tab=recentcommunityblogsdashboard
> 
> we will update the readme with this link in the new release coming up soon with lot of new features

@data-henrik This is the new link and we will update it in the marketplace and will try to maintain a wiki page.

Thanks,
Akhil
