### ISSUE TITLE
Connection to database failed: Error: [IBM][CLI Driver] SQL1598N An attempt to connect to the database server failed because of a licensing problem. SQLSTATE=42968

### ISSUE THREAD

**Issue by spufidoo** [ibmdb/vscode-extension#19]
- Platform: Windows 10 Enterprise 17134
- vscode Version: 1.4.7
- Is node.js and npm installed: yes
- node.js and npm Version: 10.16.0 and 6.9.0
- Take a screen shot of VScode(Help->About) information and paste it:

![image](https://user-images.githubusercontent.com/9607924/87303383-fe005180-c50a-11ea-947e-39164be82d17.png)

I've followed all of the instructions I can find everywhere (including issue #14 ) and I STILL get the licensing failure message.
The thing is, the ZOWE CLI DB2 plugin works perfectly, and I can connect to Db2 on z and run queries, etc.

Can someone please help me to get this running? Where do I have to put the license file? What version? 
Thanks.

**Comment by akhilravuri1** [comment]
Hi @spufidoo  

Please read the readme file.

If you have client-side license file please copy your license file under .vscode/extensions/db2connect/node_modules/ibm_db/installer/clidriver/license folder and make a connection.

Thanks,
Akhil

**Comment by spufidoo** [comment]
C:\Users\mdavage\.vscode\extensions\Db2Connect\node_modules\ibm_db\installer\clidriver\license already has the following files:
db2consv_ee.lic  
db2jcc_license_cisuz.jar  
odbc_notices.rtf  
odbc_REDIST.txt  
sam41.lic  
Windows/

and still it is not working.

**Comment by akhilravuri1** [comment]
please run db2level in your command prompt and paste the output.

Thanks,
Akhil

**Comment by spufidoo** [comment]
'db2level' is not recognized as an internal or external command,
operable program or batch file.

**Comment by akhilravuri1** [comment]
C:\Users\mdavage\.vscode\extensions\Db2Connect\node_modules\ibm_db\installer\clidriver\bin to the PATH env variable

**Comment by spufidoo** [comment]
DB21085I  This instance or install (instance name, where applicable: "*") uses
"64" bits and DB2 code release "SQL11014" with level identifier "0205010F".
Informational tokens are "DB2 v11.1.4050.860", "special_39510",
"DYN1911120100WIN64_39510", and Fix Pack "5".
Product is installed at
"C:\Users\mdavage\.vscode\extensions\Db2Connect\node_modules\ibm_db\installer\c
lidriver" with DB2 Copy Name "IBM Data Server Driver For ODBC and CLI".

**Comment by akhilravuri1** [comment]
Now please try to connect.

**Comment by spufidoo** [comment]
Still the same:
Connection to database failed: Error: [IBM][CLI Driver] SQL1598N An attempt to connect to the database server failed because of a licensing problem. SQLSTATE=42968

**Comment by akhilravuri1** [comment]
Now the issue with the version mismatch between the driver and license.
Driver version is "DB2 v11.1.4050.860", "special_39510".

View the contents of the license file in a text editor. For example, the file db2consv_ee.lic may show contents such as the following.

License Certificate for 5724-B62 IBM DB2 Connect Enterprise Edition for zSeries, V9.5

For Example, If the IBM Data Server Driver installed is from v11.1 but the license file is from v11.0. The license files are not compatible with other releases.

Thanks,
Akhil

**Comment by spufidoo** [comment]
Product version is 11.5

**Comment by akhilravuri1** [comment]
I assume an 11.5 product version means the version of the license file.

Actually 11.5 license file should work with 11.1 I mean higher license file should work with lower versions. But this is a strange case..Please give me some time, I need to do some research and reproduce the issue.

I will update you on Tuesday afternoon (India time).

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @spufidoo 

My assumption is wrong 11.5 version license file does not work with an 11.1 clidriver version.
You need to use an 11.1license file.

Thanks,
Akhil

**Comment by spufidoo** [comment]
It would be easier for me to get a 11.5 driver! Is that possible?

**Comment by akhilravuri1** [comment]
Yes..you can download the clidriver and copy the license file to the folder and make a connection.

https://www.ibm.com/support/pages/node/323035

Thanks,
Akhil

**Comment by spufidoo** [comment]
Thanks Akhil - that's perfect. It all works fine now!
