### ISSUE TITLE
DB2 Manage Connection profiles

### ISSUE THREAD

**Issue by mehtahbti** [ibmdb/vscode-extension#2]
command 'extension.Db2ManageConnProfiles' not found

**Comment by mehtahbti** [comment]
Version: 1.37.1
Commit: f06011ac164ae4dc8e753a3fe7f9549844d15e35
Date: 2019-08-15T16:16:34.800Z
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.6.0

**Comment by akhilravuri1** [comment]
Hi @mehtahbti,
 our extension is not supported on electron 4. we are planning to release the new version on Aug 30 or September 1st week. we will notify you once the new version of the extension is released.

Thanks,
Akhil

**Comment by StGoe** [comment]
We're also facing this issue. 
Looking forward to the fix. Any idea when we may expect it?

**Comment by turb0mint** [comment]
+1 Also have this problem

**Comment by akhilravuri1** [comment]
Hi @StGoe  and @turb0mint 

Thanks for using our extension and new version will be released very soon.
In that version, we will fix this profile issue.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @mehtahbti, @StGoe, and @turb0mint 

A new version of db2connect vscode extension is available in the marketplace you can update the extension and use it.

Thanks,
Akhi
