### ISSUE TITLE
Command 'Db2: Connect' resulted in an error (command 'extension.Db2Connect' not found)

### ISSUE THREAD

**Issue by spufidoo** [ibmdb/vscode-extension#20]
- Platform: Windows 10 Enterprise [Version 10.0.17134.1610]
- vscode Version: 1.49.0
- Is node.js and npm installed: yes
- node.js and npm Version: Node v12.18.3, npm 6.14.7
- Take a screen shot of VScode(Help->About) information and paste it:

Version: 1.49.0 (user setup)
Commit: e790b931385d72cf5669fcefc51cdf65990efa5d
Date: 2020-09-10T13:22:08.892Z
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

Db2Connect [windows version] v1.1.0 installed. Had been working. Upgraded node.js and npm, stopped working with "Command 'Db2: Connect' resulted in an error (command 'extension.Db2Connect' not found)" each time I try and connect.

**Comment by akhilravuri1** [comment]
Hi @spufidoo 

Please uninstall the extension and close the vscode and install the extension again.
This is because in 1.49 electron version of the vscode has been changed so need to download the latest electron binary.
So please uninstall the extension and close the vscode and install it again.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Please try to install node 12.14.1 as recommended by the vscode.

Thanks,
Akhil

**Comment by spufidoo** [comment]
- Uninstalled extension
- Closed VSCode
- Deleted \.vscode\extensions\ibm.db2connect-win-1.1.0 directory
- Upgraded to Node 14.11.0
- Started VSCode
- Installed extension
- Got these messages:
   1. Command 'Db2: Rebuild Native Modules' resulted in an error (command 'extension.Db2RebuildNativeModules' not found)
   2. Failed to rebuild native modules, please reach out to our git page for help.

**Comment by akhilravuri1** [comment]
node should be 12.14.1 for vscode 1.49

**Comment by spufidoo** [comment]
Right. I've uninstalled Node 14.11 and reinstalled 12.14.1,and I'm still getting the same messages.

**Comment by akhilravuri1** [comment]
Click on the terminal at the top and select New Terminal.
![image](https://user-images.githubusercontent.com/32290825/93482288-2e0a0d80-f91d-11ea-8fe2-784addfde324.png)

In the terminal move to the OUTPUT tab and from the dropdown select DB2Connect.
<img width="960" alt="2020_09_17_19_37_26_Db2Connect_beta docx_Word" src="https://user-images.githubusercontent.com/32290825/93482561-775a5d00-f91d-11ea-8ca9-0e92c59d8199.png">

And paste the output.

Thanks,
Akhil

**Comment by spufidoo** [comment]
[17/09/2020 15:13:42] Proceeding to rebuild native modules
[17/09/2020 15:13:42] Cleaning up the current ibm_db
Running npm install,ibm_db in c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0...
npm
 WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm
 WARN deprecated har-validator@5.1.5: this library is no longer supported

> ibm_db@2.7.1 install c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db
> node installer/driverInstall.js
platform =  win32 , arch =  x64 , node.js version =  v12.14.1

Proceeding to build IBM_DB for Electron framework...
Unable to detect electon installation.
Detected VSCode version 1.47 , will use Electron version  7.3.2

IBM_DB_HOME environment variable have already been set to -> C:\Program Files\IBM\SQLLIB
Downloading of clidriver skipped - build is in progress...

c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db>if not defined npm_config_node_gyp (node "C:\Users\mdavage\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --target=7.3.2 --arch=x64 --dist-url=https://atom.io/download/electron --IBM_DB_HOME=$IBM_DB_HOME )  else (node "C:\Users\mdavage\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" configure build  --IS_DOWNLOADED=false --target=7.3.2 --arch=x64 --dist-url=https://atom.io/download/electron --IBM_DB_HOME=$IBM_DB_HOME ) 
Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  odbc.cpp
  odbc_connection.cpp
  odbc_statement.cpp
  odbc_result.cpp
  win_delay_load_hook.cc
C:\Users\mdavage\AppData\Local\node-gyp\Cache\7.3.2\include\node\v8.h(8513,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc_statement.cpp) [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\mdavage\AppData\Local\node-gyp\Cache\7.3.2\include\node\v8.h(8522,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc_statement.cpp) [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\mdavage\AppData\Local\node-gyp\Cache\7.3.2\include\node\v8.h(8513,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc_connection.cpp) [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\mdavage\AppData\Local\node-gyp\Cache\7.3.2\include\node\v8.h(8522,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc_connection.cpp) [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\mdavage\AppData\Local\node-gyp\Cache\7.3.2\include\node\v8.h(8513,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc.cpp) [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\mdavage\AppData\Local\node-gyp\Cache\7.3.2\include\node\v8.h(8522,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc.cpp) [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\mdavage\AppData\Local\node-gyp\Cache\7.3.2\include\node\v8.h(8513,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc_result.cpp) [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
C:\Users\mdavage\AppData\Local\node-gyp\Cache\7.3.2\include\node\v8.h(8522,1): warning C4996: 'v8::MicrotasksCompletedCallback': was declared deprecated (compiling source file ..\src\odbc_result.cpp) [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_result.cpp(287,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_result.cpp(312,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_result.cpp(598,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(246,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(422,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(573,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(778,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(949,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(980,85): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(1047,91): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(1121,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_statement.cpp(1244,10): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc.cpp(216,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc.cpp(228,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(310,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(534,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc.cpp(692,73): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc.cpp(692,73): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc.cpp(693,33): warning C4311: 'type cast': pointer truncation from 'SQLHSTMT' to 'long' [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc.cpp(693,33): warning C4302: 'type cast': truncation from 'SQLHSTMT' to 'long' [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(909,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(1094,60): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc.cpp(1278,44): warning C4018: '>': signed/unsigned mismatch [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(1148,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(1178,13): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc.cpp(1394,5): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(1341,55): warning C4312: 'type cast': conversion from 'int32_t' to 'SQLPOINTER' of greater size [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(1714,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(1896,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\src\odbc_connection.cpp(2100,11): warning C4996: 'Nan::Callback::Call': was declared deprecated [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
  strptime.c
LINK : fatal error LNK1181: cannot open input file 'C:\Program Files\IBM\SQLLIB\lib\db2cli64.lib' [c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\odbc_bindings.vcxproj]
Error: Command failed: node-gyp configure build  --IS_DOWNLOADED=false --target=7.3.2 --arch=x64 --dist-url=https://atom.io/download/electron --IBM_DB_HOME=$IBM_DB_HOME
gyp ERR! build error 
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\mdavage\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\mdavage\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "build" "--IS_DOWNLOADED=false" "--target=7.3.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--IBM_DB_HOME=$IBM_DB_HOME"
gyp ERR! cwd c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
    at ChildProcess.exithandler (child_process.js:295:12)
    at ChildProcess.emit (events.js:223:5)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'node-gyp configure build  --IS_DOWNLOADED=false --target=7.3.2 --arch=x64 --dist-url=https://atom.io/download/electron --IBM_DB_HOME=$IBM_DB_HOME'
}

node-gyp build process failed! 
Proceeding with Pre-compiled Binary Installation. 

===================================
node-ibm_db installed successfully!
===================================
npm
 WARN Db2connect-win@1.1.0 No repository field.
npm
 WARN Db2connect-win@1.1.0 No license field.

+ ibm_db@2.7.1
added 1 package from 2 contributors and audited 102 packages in 25.203s
found 0 vulnerabilities
[17/09/2020 15:14:11] Finished successfully installing the component
Error: The module '\\?\c:\Users\mdavage\.vscode\extensions\ibm.db2connect-win-1.1.0\node_modules\ibm_db\build\Release\odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 75. This version of Node.js requires
NODE_MODULE_VERSION 80. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by akhilravuri1** [comment]
Hi @spufidoo 


> Detected VSCode version 1.47 , will use Electron version 7.3.2

See here your code --version displays 1.47.

But you said your vscode version is 1.49

Can you please confirm this by running ```code --version``` in the command prompt and paste the screen
![image](https://user-images.githubusercontent.com/32290825/93485227-7971eb00-f920-11ea-83fa-8f90a6dc943d.png)

Thanks,
Akhil
shot.

**Comment by spufidoo** [comment]
I uninstalled the 1.47.1 version, and everything works as normal now. Thanks for your help!
