### ISSUE TITLE
Add option to run a SQL Query stored in a file

### ISSUE THREAD

**Issue by d-carrigg** [ibmdb/vscode-extension#23]
Can the ability to run SQL scripts from files be added to this extension?  It would be ideal if this could be done via a task (so that the run/debug functionality can be leveraged) but even an additional command (i.e. DB2: Execute Script File or DB2: Execute Current File) would be nice. Basically assuming I have a setup like: 
![image](https://user-images.githubusercontent.com/16626424/98409644-db092880-2038-11eb-8d65-e83192512527.png)

I want to option to run _select.sql_ without having to copy the script into the input box.  Add icing on the cake would be to make the play button/F5 work. 

- Platform: Db2 For I (V7R2), Windows 10 client
- vscode Version: 1.50.1
- node.js version:  v14.2.0.
- npm version: 6.14.4
VS Code about box:
![image](https://user-images.githubusercontent.com/16626424/98409130-e9a31000-2037-11eb-8964-bc15af372637.png)

**Comment by akhilravuri1** [comment]
Hi @d-carrigg 

Thanks for the feedback.

we are planning to release a new version this week. In that, we have added many options. A run query option is also added in that. I will comment here once the new version is available.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @d-carrigg 

Please download the latest version of Db2 Connect(2.0.0) and try it.
Please feel free to raise an issue if you face any problem while installing or connecting.

Thanks,
Akhil
