### ISSUE TITLE
Path to copy z license file to in instructions does not exist.

### ISSUE THREAD

**Issue by patbossman** [ibmdb/vscode-extension#24]
The instructions specify:
$USERPROFILE/.vscode/extensions/db2connect/node_modules/ibm_db/installer/clidriver/license .

It looks like the new directory is:
.vscode/extensions/ibm.db2connect-2.0.0/node_modules/ibm_db/installer/clidriver

Db2 developer extension allows the user to specify the classpath rather than copy the license file, which is nice.

**Comment by akhilravuri1** [comment]
Hi @patbossman 

Yes we need to change /db2connect/ to /ibm.db2connect-version/ .

Thanks for the input.

I hope you are talking about ```IBM Db2 for z/OS Developer Extension``` this uses java driver. The license file in java driver is a jar file. So it can be added to the classpath and can be picked.

But in clidriver, the license file is .lic and db2licm(license management tool) which checks for the license checks in the absolute path of clidriver/license. So we have to manually copy the license into the above folder.

We are also palling to add an option(In vs code) called ``` Add License```  in the future release which copies the license to the clidriver path.

Please let me know if you are not looking for this or need any information.

Thanks,
Akhil

**Comment by pdbossman** [comment]
Thank you for the add license feature comment, that's what I was looking for.

**Comment by akhilravuri1** [comment]
Add license feature is supported in the 2.1.3 version. Please install the latest version to use this feature.

Thanks,
Akhil
