### ISSUE TITLE
Enhancement: Support all AUTHENTICATION methods

### ISSUE THREAD

**Issue by dlieser** [ibmdb/vscode-extension#27]
Allow saving and managing connection profiles with either (1) a full connection string, or (2) selection of any valid AUTHENTICATION method instead of only entering userid/password. 

Version: 1.54.2 (system setup)
Commit: fd6f3bce6709b121a895d042d343d71f317d74e7
Date: 2021-03-11T00:56:19.848Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Windows environment, exclusively using KERBEROS authentication to Db2 LUW and z/OS. Latter requires specification of TargetPrincipal as well.

**Comment by akhilravuri1** [comment]
Hi @dlieser 

Thanks for the comment. We will export about this feature

-Akhil

**Comment by akhilravuri1** [comment]
Hi @dlieser 

In the latest version, we have added a new tab(Optional) to enter the other properties.

Thanks,
Akhil
