### ISSUE TITLE
Back to "Failed to Rebuild Native Modules" on V2.1.3

### ISSUE THREAD

**Issue by scotdb** [ibmdb/vscode-extension#28]
I've completed removed the extension, shut VS Code, removed the relevant contents from .vscode/extensions and then reinstalled.

Still getting this annoying error.

Output log is -

[22/03/2021 22:24:21] Proceeding to rebuild native modules
[22/03/2021 22:24:21] No ibm_db found...
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip...

[0G
NaN% | 717 bytes downloaded out of NaN bytes.
[0G
NaN% | 2087 bytes downloaded out of NaN bytes.
[0G
NaN% | 3457 bytes downloaded out of NaN bytes.
[0G
NaN% | 3490 bytes downloaded out of NaN bytes.
[0G
NaN% | 4854 bytes downloaded out of NaN bytes.
[0G
... lots of downloading messages
99.97% | 26075136 bytes downloaded out of 26084194 bytes.
[0G
100.00% | 26083328 bytes downloaded out of 26084194 bytes.
[0G
100.00% | 26084194 bytes downloaded out of 26084194 bytes.
Downloading and extraction of DB2 ODBC CLI Driver completed successfully... 

Extraction of build.zip completed successfully... 

Successfully renamed the Electron binary
Error: The specified module could not be found.
\\?\c:\Users\Philip Nelson\.vscode\extensions\ibm.db2connect-2.1.3\node_modules\ibm_db\build\Release\odbc_bindings.node

I checked and the file mentioned at the end does exist (it is binary so can't verify the contents).

My system details are -

Version: 1.54.3 (system setup)
Commit: 2b9aebd5354a3629c3aba0a5f5df49f43d6689f8
Date: 2021-03-15T10:55:45.459Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

For info, I have the same version of VS Code on Linux and it installs fine.

**Comment by akhilravuri1** [comment]
Hi @scotdb 

In vscode click on view->command palette and select Developer: Toggle Developer Tools.
![image](https://user-images.githubusercontent.com/32290825/112084426-c3c57480-8bae-11eb-8a1b-a903ef8f174f.png)

Move to the console tab in the popup and please paste the log output here.

I am unable to reproduce the issue on the windows machine. That's the main reason why I am asking you to share the logs in Tools.

Thanks,
Akhil

**Comment by scotdb** [comment]
Here's the output as requested -

Error: command 'extension.Db2Connect' not found
    at C._tryExecuteCommand (commandService.ts:80)
    at commandService.ts:73
    at async T.run (actions.ts:182)
onDidChangeNotification @ notificationsAlerts.ts:38
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:622
addNotification @ notifications.ts:206
error @ notificationService.ts:58
(anonymous) @ compositePart.ts:262
fire @ event.ts:622
run @ actions.ts:185
async function (async)
run @ actions.ts:182
onClick @ menuEntryActionViewItem.ts:136
(anonymous) @ actionViewItems.ts:144
processImmediate @ internal/timers.js:456

notificationsAlerts.ts:40 Failed to rebuild native modules, please reach
out to our git page for help
onDidChangeNotification @ notificationsAlerts.ts:40
(anonymous) @ notificationsAlerts.ts:26
fire @ event.ts:622
addNotification @ notifications.ts:206
notify @ notificationService.ts:103
(anonymous) @ mainThreadMessageService.ts:83
_showMessage @ mainThreadMessageService.ts:44
$showMessage @ mainThreadMessageService.ts:38
_doInvokeHandler @ rpcProtocol.ts:417
_invokeHandler @ rpcProtocol.ts:402
_receiveRequest @ rpcProtocol.ts:318
_receiveOneMessage @ rpcProtocol.ts:245
(anonymous) @ rpcProtocol.ts:110
fire @ event.ts:622
fire @ ipc.net.ts:468
_receiveMessage @ ipc.net.ts:821
(anonymous) @ ipc.net.ts:660
fire @ event.ts:622
acceptChunk @ ipc.net.ts:241
(anonymous) @ ipc.net.ts:202
I @ ipc.net.ts:32
emit @ events.js:315
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:271
Readable.push @ _stream_readable.js:212
onStreamRead @ internal/stream_base_commons.js:186

**Comment by akhilravuri1** [comment]
Hi @scotdb 

I see \ is missing after Phillip Nelson in \?\c:\Users\Philip Nelson.vscode\extensions\ibm.db2connect-2.1.3\node_modules\ibm_db\build\Release\odbc_bindings.node is this something you missed while pasting or is was logged like this.

Thanks,
Akhil

**Comment by scotdb** [comment]
It's -

\\?\c:\Users\Philip
Nelson\.vscode\extensions\ibm.db2connect-2.1.3\node_modules\ibm_db\build\Release\odbc_bindings.node


That's "backslash backslash questionmark backslash C colon backslash Users
backslash Philip space Nelson backslash dot vscode"

Possible that the email program or webpage is dropping some of the
backslashes, treating them as escape characters?

Phil

**Comment by akhilravuri1** [comment]
Hi @scotdb 

I tried all the ways to reproduce the issue in different windows systems. Only time the issue reproduced was when .dll libs were not there.

Can you please copy the clidriver from c:\Users\Philip
Nelson\.vscode\extensions\ibm.db2connect-2.1.3\node_modules\ibm_db\installer to some other location.

After copying please set the IBM_DB_HOME = /path/to/clidriver and Add /path/to/clidriver/bin to PATH variable and install the extension.

Thanks,
Akhil

**Comment by scotdb** [comment]
Copying the clidriver elsewhere and setting the environment variables manually has fixed the issue.

**Comment by scotdb** [comment]
Shared the Win10 details privately.

**Comment by bimalkjha** [comment]
>> Copying the clidriver elsewhere and setting the environment variables manually has fixed the issue.

@scotdb If your system already have some Db2 Client or server installed; or a copy of clidriver installed at other location, it may cause conflict with the clidriver used by db2connect extension. Setting the PATH variable to point to the correct clidriver is the only solution in this case. Executing `db2cli validate` command shows list of all other copies of db2 driver installed in the system.
If there is no other copy, then we need to do some webex session to diagnose as we are unable to reproduce the problem in our system. Thanks.

**Comment by scotdb** [comment]
I had neither a preexisting Db2 Client or Server on my Windows machine.

The CLI driver I pointed to manually was the one I copied from the download
location used by your post-installer.

**Comment by annfengcn** [comment]
I face the same issue on my Mac
![image](https://user-images.githubusercontent.com/43370008/115983421-8b60ee00-a5d3-11eb-931c-48178fa9d1bb.png)

**Comment by akhilravuri1** [comment]
Hi @annfengcn 

Please share the following details:-
vscode version.
Log data from the Output tab. see https://github.com/ibmdb/vscode-extension/issues/20#issuecomment-694261954

Thanks,
Akhil

**Comment by annfengcn** [comment]
I finally find out it is caused by network issue, I have to setup VPN to download some module.

**Comment by akhilravuri1** [comment]
@annfengcn are you able to install the extension and work with it?

For downloading which module you have set up VPN?

Thanks,
Akhil
