### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by markons** [ibmdb/vscode-extension#29]
- Platform:
- vscode Version:
- Is node.js and npm installed: yes/no
- node.js and npm Version:
- Take a screen shot of VScode(Help->About) information and paste it:

Steps to Reproduce:

1.
2.

**Comment by markons** [comment]
Failed to connect to 192.168.1.75/sample. Error: Unable to set DB2 version information: DB2 SQL Error: SQLCODE=-440, SQLSTATE=42884, SQLERRMC=GETVARIABLE;FUNCTION, DRIVER=4.27.25

Any help pls.?

**Comment by akhilravuri1** [comment]
Hi @markons 

Are you getting this error while connecting?

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Can you please paste the connection stroing you have used?
The parameters which you used are for different extension and this is a different extension.
In this extension, you don't need to set any parameters.

Thanks,
Akhil

**Comment by markons** [comment]
Hi Akhil,

sorry for the late answer. Here the connection URL:

*jdbc:db2://192.168.x.yyy:50000/SAMPLE*

FYKI, I've coded a Java snippet to test this URL, which run without any
problem:

[image: image.png]


Regards
Gabor


Am Mo., 29. März 2021 um 12:35 Uhr schrieb Akhil Ravuri <
***@***.***>:

**Comment by akhilravuri1** [comment]
Hi @markons 

This extension uses odbc driver. So connection has to be in this format:
```
database=db1;hostname=localhost;port=4010;uid=2222;pwd=11111
```
We have shown this also in the background of the input box.
![image](https://user-images.githubusercontent.com/32290825/112875806-489a1c00-90e2-11eb-9c6f-b059a601434f.png)

Please let me know if you face any issues.
Thanks,
Akhil

**Comment by markons** [comment]
Hi Akhil,

sorry, I've used previously another extension...

Now I've installed the right one. Actually, it ends with another error:

Connection to database failed: Error: [IBM][CLI Driver] SQL1042C  An
unexpected system error occurred.  SQLSTATE=58004

Regards,
Gabor

Am Mo., 29. März 2021 um 19:30 Uhr schrieb Akhil Ravuri <
***@***.***>:

**Comment by akhilravuri1** [comment]
Hi @markons 

I assume you are using our extension on windows 10.
In Windows 10 some of the DLLs are missing in system32.
If you are on windows 10 please add this ``` path\to\clidriver\bin\amd64.VC12.CRT``` to your path variable and close the vscode and open it again so that vscode picks the updated path. (If you are using the clidriver download by the extension your path will be ``` C:\Users\uname\.vscode\extensions\ibm.db2connect-2.1.3\node_modules\ibm_db\installer\clidriver\bin\amd64.VC12.CRT ```)

If you are facing any issues please let me know.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @markons 

Is your issue resolved?

Thanks,
Akhil

**Comment by markons** [comment]
Hi,

unfortunately not, I get the same error:

Connection to database failed: Error: [IBM][CLI Driver] SQL1042C  An
unexpected system error occurred.  SQLSTATE=58004

Here my path setting:

[image: image.png]

Which shows to this content:

[image: image.png]

Regards
Gabor

Am Do., 1. Apr. 2021 um 07:48 Uhr schrieb Akhil Ravuri <
***@***.***>:

**Comment by akhilravuri1** [comment]
HI @markons 

images are uploaded can you upload it again.

Thanks,
Akhil

**Comment by markons** [comment]
Hi,

I don't understand. Can't you see the uploaded images?

But here the content of the directory (second image):

Verzeichnis von
*C:\Users\pc\.vscode\extensions\ibm.db2connect-2.1.3\node_modules\ibm_db\installer\clidriver\bin\amd64.VC12.CRT*

29.03.2021  19:37    <DIR>          .
29.03.2021  19:37    <DIR>          ..
29.03.2021  19:37               431 amd64.VC12.CRT.manifest
29.03.2021  19:37           660.128 msvcp120.dll
29.03.2021  19:37           963.232 msvcr120.dll
               3 Datei(en),      1.623.791 Bytes
               2 Verzeichnis(se), 107.319.177.216 Bytes frei

The first image shows the path, where the above path is very well included.

Regards


Am Do., 1. Apr. 2021 um 10:11 Uhr schrieb Akhil Ravuri <
***@***.***>:

**Comment by akhilravuri1** [comment]
Hi @markons 

Sorry for the late reply.
Can you please check whether that server is running or not?

Thanks,
Akhil

**Comment by markons** [comment]
Hi Akhil,

if I (auto)start the Db2, I get following error at opening the extension:

"The Db2 SQL Service could not be started because the specified port
(50000) is already in use"

Regards
Gabor

Am Mo., 5. Apr. 2021 um 08:00 Uhr schrieb Akhil Ravuri <
***@***.***>:

**Comment by markons** [comment]
Hi,

now it is OK with the connection. I've used the default port number 4010 in
the settings, and the above error message shows something false.
I've set it to 50000 to use the right one.

Thanks for your kind help!

Regards
Gabor

Am Mi., 7. Apr. 2021 um 09:42 Uhr schrieb Gabor Markon ***@***.***>:
