### ISSUE TITLE
V 1.1 Not working in latest version of vscode

### ISSUE THREAD

**Issue by turb0mint** [ibmdb/vscode-extension#3]
Just downloaded the new version. All commands unavailable. Have uninstalled and reinstalled extension several times.

![image](https://user-images.githubusercontent.com/35158378/66906299-5b5c8600-efff-11e9-8339-c2a362342b40.png)

**Comment by akhilravuri1** [comment]
please give us some more information like vscode version and platform.

Thanks,
Akhil.

**Comment by turb0mint** [comment]
Just noticed this in the output window, I'm presuming I'm missing a dependency, I have the db2 odbc client drivers installed

[16/10/2019 11:05:02] Proceeding to rebuild native modules
[16/10/2019 11:05:02] No ibm_db found...
Running npm install,ibm_db in c:\Users\xxxx\.vscode\extensions\ibm.db2connect-win-1.1.0...
'npm' is not recognized as an internal or external command,
operable program or batch file.
[16/10/2019 11:05:02] ibm_db installation failed with code: 1
Error: Failed to execute command "npm" with  arguments "install, ibm_db" return code 1

**Comment by akhilravuri1** [comment]
Thanks for info.
you need to install node js and npm to use this extension.
