### ISSUE TITLE
Command 'Db2: Connect' resulted in an error (command 'extension.Db2Connect' not found)

### ISSUE THREAD

**Issue by cia05rf** [ibmdb/vscode-extension#30]
I'm having an issue running the db2 extension on VSCode.

`command 'extension.Db2Connect' not found`

output log is 

```
[10/05/2021 16:11:18] Proceeding to rebuild native modules
[10/05/2021 16:11:18] No ibm_db found...
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip...

[0G
0.01% | 512 bytes downloaded out of 4714942 bytes.
100.00% | 4714942 bytes downloaded out of 4714942 bytes.
Downloading and extraction of node ibm_db Driver completed successfully... 

Successfully renamed the directory.
Using the existing CLI Driver
C:\Users\robert.franklin\.vscode\extensions\ibm.db2connect-2.1.4\node_modules\ibm_db\installer\clidriver
Extraction of build.zip completed successfully... 

Error: ENOENT: no such file or directory, rename 'c:\Users\robert.franklin\.vscode\extensions\ibm.db2connect-2.1.4\node_modules\ibm_db\build\Release\odbc_bindings_win_12.node' -> 'c:\Users\robert.franklin\.vscode\extensions\ibm.db2connect-2.1.4\node_modules\ibm_db\build\Release\odbc_bindings.node'
```

Versions:
VSCode: 1.56.0
npm: 6.14.12
node: v14.16.1

**Comment by akhilravuri1** [comment]
Hi @cia05rf 

vscode 1.56 uses electron 12 version. we will create the new binary against electron 12 and we will upload it.
Please give us some time.

Thanks,
Akhil

**Comment by cia05rf** [comment]
Ok, how much time do you think it'll be?

**Comment by akhilravuri1** [comment]
@cia05rf By Wednesday evening we will upload the latest binary.

If you want to use the extension please install vscode version<=1.55.x 

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @cia05rf 

Sorry for the delay.
We have uploaded the latest binary. Please uninstall and install the extension.
If you face any issues please let us know.

Thanks,
Akhil

**Comment by cia05rf** [comment]
No, this is still not solved. I'm on `1.56.2`

**Comment by akhilravuri1** [comment]
In our environment, it is working fine.

Can you please paste the error from your output log?

If not please uninstall the extension and install it again.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
@cia05rf are you able to install?

Thanks,
Akhil
