### ISSUE TITLE
Data with Japanese charcters are not displayed

### ISSUE THREAD

**Issue by kyokonishito** [ibmdb/vscode-extension#32]
### We can not display any Japanese charcters.

- Platform: Mac Catalina 10.15.7
- vscode Version: 15.7.1
- Is node.js and npm installed: yes
- node.js and npm Version: v14.15.4 and 6.14.10
- Take a screen shot of VScode(Help->About) information and paste it:
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Connect to a db2 db
2. Show  the tree view and we can not see Japanese characters in a table name. The actual table name is `COVID_19_東京`.
![image](https://user-images.githubusercontent.com/40123488/125383171-f56a8180-e3d1-11eb-857d-1301f835dd1b.png)

2. Click  a table name `COVID_19_` which has all column names with Japanese characters from the tree view . We can not see any colum names and we received `No COLUMNS in this tables` error.
![image](https://user-images.githubusercontent.com/40123488/125392492-361dc700-e3e1-11eb-9bb5-3379d9f6d0a4.png)

2. Right click  a table name `COVID_19_`  and click 'Select Top 1000', then we received an error `Query execution failed: Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0204N "NISHITO.COVID_19_ " is an undefined name. SQLSTATE=42704`.
![image](https://user-images.githubusercontent.com/40123488/125393393-d9231080-e3e2-11eb-8733-d56326d928bb.png)

2.  Right click  a table name `MEMBER` which has Japanese characters in `NAME` column and click 'Select Top 1000', then we can not see any Japanese characters in `NAME` column.
![image](https://user-images.githubusercontent.com/40123488/125393639-4d5db400-e3e3-11eb-8b3c-b1e930d14e82.png)

I attached the images with [DBeaver](https://dbeaver.io/) which is an OSS tool , can display Japanese correctly for your infomation:
![image](https://user-images.githubusercontent.com/40123488/125394004-e7bdf780-e3e3-11eb-9a60-c75c51299987.png)

**Comment by akhilravuri1** [comment]
Hi @kyokonishito 

I will try to reproduce the issue.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @kyokonishito 

I am able to reproduce the issue.
I Will let you know if this can be solved using a change in settings or env.

Thanks,
Akhil

**Comment by kyokonishito** [comment]
I confirmed Japanese characters can be displayed with v2.3.0. Thanks.
