### ISSUE TITLE
odbc_bindings_win_13.node missing from downloaded https://github.com/ibmdb/node-ibm_db/archive/master.zip

### ISSUE THREAD

**Issue by leebehrens** [ibmdb/vscode-extension#33]
- Platform: Windows 10
- vscode Version: 1.59.0
- Is node.js and npm installed: node.js
- node.js and npm Version: node.js 14.16.0
- Take a screen shot of VScode(Help->About) information and paste it:
Version: 1.59.0 (user setup)
Commit: 379476f0e13988d90fab105c5c19e7abc8b1dea8
Date: 2021-08-04T23:13:12.822Z
Electron: 13.1.7
Chrome: 91.0.4472.124
Node.js: 14.16.0
V8: 9.1.269.36-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Install (or remove, restart VSCode, reinstall) Db2 Connect
2. Click the Db2 Connect's extension icon
3. Click Db2 Connect's Connect button

Error: Failed to rebuild native modules, please reach out to our git page for help

Log:
```
[8/5/2021 4:35:49 PM] Proceeding to rebuild native modules
[8/5/2021 4:35:49 PM] No ibm_db found...
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip...

[0G
NaN% | 716 bytes downloaded out of NaN bytes.
[0G
NaN% | 2086 bytes downloaded out of NaN bytes.
[0G
. . .
NaN% | 5553095 bytes downloaded out of NaN bytes.
Downloading and extraction of node ibm_db Driver completed successfully... 

Successfully renamed the directory.
Using the existing CLI Driver
C:\Program Files\ibm\SQLLIB\clidriver
Extraction of build.zip completed successfully... 

Error: ENOENT: no such file or directory, rename 'c:\Users\omitted\.vscode\extensions\ibm.db2connect-2.2.0\node_modules\ibm_db\build\Release\odbc_bindings_win_13.node' -> 'c:\Users\omitted\.vscode\extensions\ibm.db2connect-2.2.0\node_modules\ibm_db\build\Release\odbc_bindings.node'
```

Found build.zip contains all the files in `build\Release`. Does not contain `odbc_bindings_win_13.node`. Tried copying `odbc_bindings_win_12.node` to `odbc_bindings.node`, but Db2 Connect still didn't work.

Looked in https://github.com/ibmdb/node-ibm_db, and find that `odbc_bindings_win_13.node` does not exist in the project (or in `build.zip`, etc. in the project.

Note that before the VSCode update to 1.59.0, Db2 Connect worked for me.

**Comment by akhilravuri1** [comment]
Hi @leebehrens 

Electron 13 binary which is released recently is not added to that repo.
We will add it by the EOD.
Sorry for the trouble.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @leebehrens 

Pushed the latest electron binaries. Please click on rebuild native modules and try to establish a connection.

If any issue occurs please let me know.

Thanks,
Akhil

**Comment by kentsellers** [comment]
I just tried downloading the extension for the first time and the same thing is happening. There is no file 13, but there is 19-26. I don't have the latest VS Code installed, could that be the problem? Or is there something else?

**Comment by bimalkjha** [comment]
@kentsellers Yes, please upgrade your vscode as 13 version of electron is too old and it was coming with more than 2 year old vscode. Alternatively, you can try installing older version of this extension if vscode support it. Thanks.
