### ISSUE TITLE
Cannot connect to DB2 LUW with SSL

### ISSUE THREAD

**Issue by htdinh13** [ibmdb/vscode-extension#36]
Hi team,

When trying to connect to my database with option 1 with connection string:
`DATABASE=<<dbname>>;HOSTNAME=<<hostname>>;PORT=<<port>>;PROTOCOL=TCPIP;UID=xxxxx;PWD=xxxxx;security=ssl`

I'm having following error:
`SQL30081N A communication error has been detected. Communication protocol being used: "SSL". Communication API being used: "SOCKETS". Location where the error was detected: "". Communication function detecting the error: "sqlccSSLSocketSetup". Protocol specific error code(s): "414", "*", "*". SQLSTATE=08001`

Did I miss anything in my connection string?

My system details are:
OS: macOS 11.6 (20G165)
VSCode version: 1.62.3 (Universal)
DB2 Connect version: v2.3.0

**Comment by amukherjee28** [comment]
Hi @htdinh13 

The reason behind a getting a Communication failure could a wide range of possibilities.

I can narrow down a few reason which could be the most common reasons.

1. In the above connection string example, you have only security=ssl. Assuming you are trying a connection to the cloud (ibm cloud where you dont need a certificate from the server) please check again if the port number used in the connection string is the SSL port.
2. In case you are not connecting to the cloud and using your own SSL setup, I will strongly suggest you to use the SSLSERVERCERTIFICATE key word along with the connection string and point the value of the proper server certificate that you might have acquired from the server for proper handshake to happen.

From the error code itself looks like you are hitting ssl error 414 and documentation of the same suggests

```GSKit: 414
This return code indicates that an incorrectly formatted certificate was received from the partner in an TLS relationship.

This error can be returned in these scenarios:
You are using self-signed certificates and the certificate is missing.
The certificate that is being used is from a local certificate authority that does not have the Basic Constraints extension active.
Note: You can use the ALLOW_NONCRITICAL_BASIC_CONSTRAINT keystore configuration parameter to bypass this problem.```

So looks like you will need a proper certificate for the connection to go through.

In case you want more information on the keyword, please go through the following link

https://www.ibm.com/docs/en/db2/11.1?topic=keywords-sslservercertificate

**Comment by htdinh13** [comment]
Thank @amukherjee28 for your response, I can resolve the issue with SSLSERVERCERTIFICATE.
