### ISSUE TITLE
Select Query return invalid value for big int type

### ISSUE THREAD

**Issue by venkateshkuppusamy** [ibmdb/vscode-extension#38]
I have a select query, with bigint type column returns invalid value eg. the actual value is 3074457345616810458 but returns 3074457345616810500. 
I think this is some sort of rounding off problem with bigint type. I have to cast to varchar to get the right value in the select results. 

Can you confirm this behavior and is there a fix for this.

**Comment by amukherjee28** [comment]
@venkateshkuppusamy 

I am able to see this in my local repro. Working on this to get to the cause.

Meanwhile can you provide a bit more details of the server you are connecting to. Are you using DB2/LUW server and getting the bigint value rounded off?

Thanks

**Comment by bimalkjha** [comment]
@venkateshkuppusamy Look on https://github.com/ibmdb/node-ibm_db/issues/816. This behavior may be expected if you have bigger data in DB that JS can not handle. Thanks.
