### ISSUE TITLE
Failed to rebuild native modules, please reach out to our git page for help

### ISSUE THREAD

**Issue by GerMFHub** [ibmdb/vscode-extension#39]
- Platform: Windows 10
- vscode Version: 1.64.1
- Is node.js and npm installed: yes
- node.js and npm Version: v14.18.3
- Take a screen shot of VScode(Help->About) information and paste it:

Steps to Reproduce:

Tried to install Db2 connect plugin and add new connection profile and then started to get an errors like:  db2 connect extension not found, db2 manage connection profile is not found and etc. Tried different version of Db2 connect - same story. Deleted  Db2 connect folders from .vscode\extensions - did not help, getting same errors

![image](https://user-images.githubusercontent.com/41899904/153442367-1be159b2-501c-4191-b002-dd98d4b1fb82.png)

**Comment by amukherjee28** [comment]
@GerMFHub 

I did test the plugin in VSCODE version 1.62.2

Electron version : 13.5.2

Windows 10

Things are working fine.
May I suggest you  the following.

Uninstall the plugin.
Delete the folder structure ```.vscode\extensions\ibm.db2connect-2.3.0```

This should remove everything related to plugin.

Now install the plugin in VSCODE.

If it does not work then send us the following log.
GOTO VSCODE -> Terminal -> New Terminal

In the terminal go the OUTPUT tab. From the drop down on the upper right corner of the terminal select Db2Connect.

Send whatever log you see there.

**Comment by GerMFHub** [comment]
did as you suggested, but plugin still fails. Sending you terminal output. 
[DB2Connect terminal output.txt](https://github.com/ibmdb/vscode-extension/files/8061014/DB2Connect.terminal.output.txt)

**Comment by amukherjee28** [comment]
@GerMFHub sorry for coming back on this late.

I saw the attached output that you have send and looks like the end line has some issues.

First of all in your case while the native module is getting rebuild I see that clidriver installation/download is skipped.
So this means that you have IBM_DB_HOME path set in your machine. I this a correct assumption from my end?

Also in that end while the pre existing binary is downloaded and renamed I see the following error

```
Successfully renamed the directory.
Using the existing CLI Driver
C:\Users\user\IBM\SDPShared\plugins\com.ibm.datatools.db2_2.3.0.202010040418\driver\db2jcc4.jar
Extraction of build.zip completed successfully... 

Successfully renamed the Electron binary
Error: The specified module could not be found.
\\?\c:\Users\user\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\build\Release\odbc_bindings.node

```

where is in my case 

```
c:\Users\amukherjee\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\installer\clidriver
Extraction of build.zip completed successfully... 

Successfully renamed the Electron binary
``` 

Not sure why you have db2jcc4.jar getting downloaded and error in the end of the statement.

Could you tell me if anything else changed in the environment apart from VSCODE version in your machine.

**Comment by GerMFHub** [comment]
IBM_DB_HOME was created as a part of IBM RDz installation. Removed that and this seems to be working. Thanks
