### ISSUE TITLE
command 'extension.Db2ManageConnProfiles' not found

### ISSUE THREAD

**Issue by StGoe** [ibmdb/vscode-extension#4]
Hello,

after installing the updatde version, I'm still getting errors: 

command 'extension.Db2ManageConnProfiles' not found
Failed to rebuild native modules, please reach out to our git page for help

thx

**Comment by akhilravuri1** [comment]
please give us some more information like vscode version and platform.

Thanks,
Akhil.

**Comment by akhilravuri1** [comment]
please install node js and npm to use this extension.
As this extension uses node js driver internally you need to install node js and npm to use this extension.

**Comment by arnelbaloyo** [comment]
Hi,

Getting the same error:
command 'extension.Db2ManageConnProfiles' not found
Failed to rebuild native modules, please reach out to our git page for help

Version: 1.40.0
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Appreciate if someone can help. Thanks.

**Comment by akhilravuri1** [comment]
Hi @StGoe 
please uninstall and install the extension.
we have fixed the issue.

Thanks,
Akhil
