### ISSUE TITLE
VSCode 1.66 update - failed to rebuild the native modules

### ISSUE THREAD

**Issue by galczynskiCS** [ibmdb/vscode-extension#42]
- Platform: Windows
- vscode Version: 1.66
![image](https://user-images.githubusercontent.com/26344302/161787234-522c83fc-6633-4c20-a820-bcfe00aa71ce.png)

Steps to Reproduce:

1. Updated to 1.66
2. DB2 Connect stopped working (could not connect)
3. Reinstalled the DB2 Connect
4. Failed to rebuild the native modules

`
Intellisense Activated
[4/5/2022 5:10:19 PM] Proceeding to rebuild native modules
[4/5/2022 5:10:19 PM] Cleaning up the current ibm_db
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip...
Downloading and extraction of node ibm_db Driver completed successfully... 

Successfully renamed the directory.
platform = win32, arch = x64, node.js version = v16.13.0
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...

Downloading and extraction of DB2 ODBC CLI Driver completed successfully... 

c:\Users\U013556\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\installer\clidriver
Extraction of build.zip completed successfully... 

Error: ENOENT: no such file or directory, rename 'c:\Users\U013556\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\build\Release\odbc_bindings_win_17.node' -> 'c:\Users\U013556\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\build\Release\odbc_bindings.node'
`

**Comment by Tal-Daniel** [comment]
Same issue on VS Code 1.66, macOS.
 
Seems there is no support for Electron version 17, as there only bindings up to 13 exist in Release folder, so error in extension.js, function renameElectronBinary()

**Comment by amukherjee28** [comment]
We have updated the binaries after building it with latest electron versions.
Please try installing again or use option "rebuild native modules".

This will download the latest code base which contains the new binaries build with electron 17 version.

Thanks.

**Comment by galczynskiCS** [comment]
Works like a charm. 
Thank you for your help.
