### ISSUE TITLE
.sql and .db2 files won't run with single line comments

### ISSUE THREAD

**Issue by THWU0412** [ibmdb/vscode-extension#43]
Hi, maybe it's a personal setup problem (SQL and DB2 beginner here), but I haven't found any information about this on any other platform.

If I run a .sql or .db2 file that has comments somewhere in it, the query after the comment will not be executed.
This only happens with single line comments (```-- comment```). Multi line comments (```/* comment */```) work.

Version: 1.67.0
Commit: 57fd6d0195bb9b9d1b49f6da5db789060795de47
Datum: 2022-05-04T12:14:47.100Z (Vor 5 Tagen)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
Betriebssystem: Darwin x64 21.4.0

**Comment by bimalkjha** [comment]
@THWU0412 Please share your sample .sql or .db2 file which reproduces the issue. Basically, anything after `--` sign is regarded as comment till the end of the line. So, if you type SQL after your `--comment SQL`, the SQL too will be treated as part of comment. So, it may be working as designed, but to rule out any other scenario, we want to see your test file. Please attach here. Thanks.

**Comment by bimalkjha** [comment]
@THWU0412 If you do not add delimiter at end of single line comment, the next SQL get joined with the previous line and the combination becomes comment. Hence, get ignored. Add statement terminator (default semicolon) at the end of single line comment to separate it from next SQL. Below .sql file works fine:
```
/* select only pid and price */
select pid, price from newton.product;
-- slect only pid;
select pid from newton.product;
select price from newton.product;
```
Thanks.

**Comment by bimalkjha** [comment]
FIx for this issue has been delivered as [this commit](https://git.rocketsoftware.com/projects/DBCT/repos/vscode/commits/a368dcc4cbd0410cdd6078fe6daa09b785b41167) and it will be part of next release. Hence, closing the issue. Thanks.
