### ISSUE TITLE
Informix support

### ISSUE THREAD

**Issue by luizfgemi** [ibmdb/vscode-extension#44]
Can you include Informix query support?

**Comment by bimalkjha** [comment]
@luizfgemi We do not have much experience about Informix SQL. We assume, this vscode extension should work with IDS also if DRDA port is enabled on server and onsoc drda is used in connection string.
Intellicense - Few IDS specific syntax may not work, but sql should be fine. 
Please share the details about specific issue that you see with repro steps. Thanks.
