### ISSUE TITLE
extension does not work on rhel8 

### ISSUE THREAD

**Issue by gszoeke** [ibmdb/vscode-extension#45]
- Platform:  RHEL8.6
- vscode Version: 1.67.2
- Is node.js and npm installed: yes
- node.js and npm Version: 16.13.0
- Take a screen shot of VScode(Help->About) information and paste it:

Steps to Reproduce:

Install db2 extension and try use it.
Debug output :
--------------------------------------------------------------
....
Downloading and extraction of node ibm_db Driver completed successfully... 

Successfully renamed the directory.
Using the existing CLI Driver
/home/johndoe/sqllib
Extraction of build.zip completed successfully... 

Error: ENOENT: no such file or directory, rename '/home/johndoe/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/build/Release/odbc_bindings_linux_17.node' -> '/home/johndoe/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/build/Release/odbc_bindings.node'

-------------------------------------------------------------------

As it looks the extension expects node.js which can handle electron 17 

![image](https://user-images.githubusercontent.com/107393525/173310235-660b7298-04cb-4298-8554-896fd244f0e0.png)

**Comment by bimalkjha** [comment]
@gszoeke Rebuild the native module or go for fresh installation. It should work now. We have added support for electron 17 and electron 18 on Linux. Please update here about the result. Thanks.
