### ISSUE TITLE
Connection to database failed: Error: [IBM][CLI Driver] SQL30082N Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID"). SQLSTATE=08001

### ISSUE THREAD

**Issue by hoangtony21184** [ibmdb/vscode-extension#46]
So I have installed DB2 following this instruction: https://ajstorm.medium.com/installing-db2-on-your-coffee-break-5be1d811b052

However, I could not connect to DB2 via the VSCode extension with the following error

Connection to database failed: Error: [IBM][CLI Driver] SQL30082N Security processing failed with reason "24" ("USERNAME AND/OR PASSWORD INVALID"). SQLSTATE=08001

Please help, thank you :)

**Comment by bimalkjha** [comment]
@hoangtony21184 What is the output of db2level command? Are you able to connect to Db2 server using any other client?
This error tells either the userid or password is incorrect. If you have any special character in password, then enclose it between single quote and try. Thank.

**Comment by bimalkjha** [comment]
Closing the issue due to inactivity. We can reopen it once you share the requested info. Thanks.
