### ISSUE TITLE
Failed to rebuild native modules

### ISSUE THREAD

**Issue by galczynskiCS** [ibmdb/vscode-extension#48]
- Platform: Windows 11
- vscode Version: 1.69.2
- Is node.js and npm installed: 
- node.js and npm Version:
- Take a screen shot of VScode(Help->About) information and paste it:
![image](https://user-images.githubusercontent.com/26344302/182806159-633574f1-9de8-4118-96de-9c4c2497a97b.png)

Steps to Reproduce:

1. Open VSCode
2. Select DB2 extension from ribbon
3. Select Connect
4. 
![image](https://user-images.githubusercontent.com/26344302/182806659-0e18910c-98fb-4852-a0a2-18716891fcc9.png)

I did try to reinstall the db2 extension. It didn't help.

**Comment by bimalkjha** [comment]
@galczynskiCS Please find the file `C:\Users\bjha\.vscode\extensions\ibm.db2connect-2.3.0\rebuilt_dont_delete` and delete it. Then close the VSCode and reopen it. Try to use connection. It should go for rebuild native module and fix the issue.
You can check the rebuild log as in below screen shot and share here if rebuild fails. You may check issue #28 to know how output log looks and other solutions. Thanks.
![image](https://user-images.githubusercontent.com/11818648/182826428-9bd26efa-3d0f-47fb-8139-16ea18b45237.png)

**Comment by galczynskiCS** [comment]
Hi @bimalkjha,

There is no rebuilt_dont_delete file neither in the repository you mentioned, nor in the extension folder itself.
![image](https://user-images.githubusercontent.com/26344302/182830325-e7a6b314-1499-420b-ae03-43c05bcd8f51.png)

**Comment by bimalkjha** [comment]
@galczynskiCS Then delete the directory `C:\Users\youruserid\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db` manually and restart vscode. Try to capture the output log as mentioned in previous update. Thanks.

**Comment by bimalkjha** [comment]
If still do not work, then run below commands from windows command prompt, reopen vscode, verify and share the complete output from command prompt:
```
cd C:\Users\YOURUSERID\.vscode\extensions\ibm.db2connect-2.3.0\
npm uninstall ibm_db
npm install ibm_db
```
I hope you are using ibm.db2connect-2.3.0, if your is different let us know.
Try to uninstall the extension and go for fresh installation. New installation should fix the issue. Thanks.

**Comment by bimalkjha** [comment]
If you are on slack, ping me on bjha26@iespc.ibm.com. Thanks.

**Comment by galczynskiCS** [comment]
Hi @bimalkjha 
I've deleted the folder, but I still can't install the extension. I've captured the log on new installation.

Intellisense Activated
[8/16/2022 1:00:52 PM] Proceeding to rebuild native modules
[8/16/2022 1:00:52 PM] No ibm_db found...
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip...

Error: read ECONNRESET

**Comment by galczynskiCS** [comment]
@bimalkjha  
The thing is that my internet connection works correctly. I can download the extension manually. I can operate within VScode, download extensions etc. 
I'm a bit puzzeled why the ECCONNRESET error pops up.

**Comment by bimalkjha** [comment]
@galczynskiCS  From VSCode, click on `View -> Command Palette -> Db2: Rebuild Native Modules`. Then, click on `View -> Output` and it will open output windows. In the output windows, select `Db2Connect` in Task as in below screen shot:
![image](https://user-images.githubusercontent.com/11818648/185182298-0de595be-248d-4e1a-9463-0f51eb3a1b83.png)

It should reinstall db2connect extension and extension should work fine. If there is any error in the `Output` window, please copy the text and share here. Thanks.

**Comment by galczynskiCS** [comment]
@bimalkjha I did as you instructed. The error I get right now is:
![image](https://user-images.githubusercontent.com/26344302/185388646-68ca1747-f6a3-41e9-9df8-ab93b2c1d82b.png)

**Comment by bimalkjha** [comment]
@galczynskiCS It should proceed to download till 7278220 bytes. Looks some issue with your internet is blocking further download. Please retry installing db2connect extension and see if issue persists. I just installed on a fresh new Windows 11 system and db2connect extension installed without any issue with blow output:
```
NaN% | 7278220 bytes downloaded out of NaN bytes.
Downloading and extraction of node ibm_db Driver completed successfully... 

Successfully renamed the directory.
platform = win32, arch = x64, node.js version = v16.13.2
Downloading DB2 ODBC CLI Driver from https://public.dhe.ibm.com/ibmdl/export/pub/software/data/db2/drivers/odbc_cli/ntx64_odbc_cli.zip...
.........
```
Thanks.

**Comment by galczynskiCS** [comment]
I believe we can close this one. I did the same on my other machine and it works.
Right now I receive error SOCKET CLOSED. Seems like it's an internal company network policy or issue.
