### ISSUE TITLE
"command 'extension.Db2ManageConnProfiles' not found"

### ISSUE THREAD

**Issue by adrianoafcs** [ibmdb/vscode-extension#49]
- Platform: Mac Monterey 12.4
- vscode Version: 1.70.1
- node.js: v18.7.0
- code: 1.70.1 arm64
- npm: 8.15.0

Steps to Reproduce:

1. I've installed VScode and then Cobol extension;
2. I've installed DB2 Connect;
3. I've clicked on Command Palete DB2: Manage Connection Profile;

I've already tried to reinstall npm and node but the error is the same. My goal is create a DB2 database to connect with Cobol.

**Comment by bimalkjha** [comment]
@adrianoafcs Db2 Connect extension works only with "intel chip" version of vscode like https://code.visualstudio.com/docs/?dv=darwinx64 . It does not work with Universal or Apple Silicon version of vscode.

The code version should not show `arm64`. Db2Connect extension does not support arm64 architecture. Thanks.

**Comment by bimalkjha** [comment]
To create Db2 database, you can directly login on the system where Db2 server is installed and run `db2 create db <dbname>` command on command prompt. Thanks.

**Comment by adrianoafcs** [comment]
@bimalkjha Thank you for helping me.

I’ve bought a Mac M1 a few months ago and now I’m dealing with hard problem to create a cobol and bd2 environment.

I also tried create a VM for windows but it’s also with problem with M1 chip. (virtualbox).

Do you know some way to help me to create a cobol and db2 in cloud or any software for m1 chip ?

**Comment by bimalkjha** [comment]
@adrianoafcs To create a Db2 database, there should Db2 server installed. Do you have any Db2 server image installed on any system to which you want to connect and create database? Please share the output of `db2level` command from Db2 server system.
There is no Cobol compiler for M1 Chip system that can be used to connect to Db2. The supported OS for Db2 application development in Cobol is documented here: https://www.ibm.com/docs/en/db2/11.5?topic=compilers-cobol
It seems there is no cobol compiler for M1 Chip system and you can not have cobol env on this laptop.
This M1 chip system comes with arm64 architecture which is not supported by Db2. You should look for some intel chip system. Thanks.

**Comment by bimalkjha** [comment]
@adrianoafcs Any other info required from us? I think "command 'extension.Db2ManageConnProfiles' not found" issue is resolved now. So, can we close this issue now? Thanks.
