### ISSUE TITLE
Help: Failed to rebuild native modules, please reach out to our git page for help

### ISSUE THREAD

**Issue by arnelbaloyo** [ibmdb/vscode-extension#5]
Hi,

Getting the same error:
command 'extension.Db2ManageConnProfiles' not found
Failed to rebuild native modules, please reach out to our git page for help

Output console:
.vscode/extensions/ibm.db2connect-1.1.0/node_modules/ibm_db/build/Release/odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 73. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

Vscode:
Version: 1.40.0
Date: 2019-11-06T17:09:34.601Z
Electron: 6.1.2
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

Appreciate if someone can help. Thanks.

**Comment by akhilravuri1** [comment]
Hi @arnelbaloyo 
sorry for the late reply...
I am able to reproduce the issue I am working on it.

Thanks,
Akhil

**Comment by arnelbaloyo** [comment]
@akhilravuri1 , thanks for looking into this.

**Comment by akhilravuri1** [comment]
Hi @arnelbaloyo 
we are facing some problems with the vscode node version which is used to build node_ibmdb driver.
We are fixing the problems it may take 2-3 days more.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @arnelbaloyo 
Please uninstall and install the extension.
we have updated our node driver code.

Thanks,
Akhil

**Comment by arnelbaloyo** [comment]
thanks a lot @akhilravuri1 ... this is working perfectly for me now! Appreciate it!

**Comment by smithprasadgit** [comment]
I am getting Failed to rebuild native modules, please reach out to our git page for help While using DB2 Connect command through Visual Code. Can some one help

**Comment by akhilravuri1** [comment]
Hi @smithprasadgit 

Please provide version details, platform.

Is node js installed in your system?

Please check this comment on how to take the logs...https://github.com/ibmdb/vscode-extension/issues/20#issuecomment-694261954

And paste the log data here.

Thanks,
Akhil

**Comment by smithprasadgit** [comment]
VScode: 1.52.1
OS: Windows
node js is installed, version:14.15.4
In terminal I am not getting DB2 Coonect option in the dropdown. when I am trying to run the command from pallette i am getting the below errors. 
![error](https://user-images.githubusercontent.com/47138984/105161006-e5ff2f80-5b36-11eb-88ec-ce4b530d52bb.png)

**Comment by akhilravuri1** [comment]
Uninstall the extension.
Close the vscode.
Install node.js 12.14 version.
After the installation of node.js please open vscode and install the extension.
If face any issue after that also...please follow the #20(comment) and give the log.

Thanks,
Akhil

**Comment by smithprasadgit** [comment]
I did the above steps also, but no luck

**Comment by akhilravuri1** [comment]
please run node --version in your terminal and paste the output?

**Comment by akhilravuri1** [comment]
Please paste the screenshot

**Comment by smithprasadgit** [comment]
![image](https://user-images.githubusercontent.com/47138984/105167031-3332cf80-5b3e-11eb-99bd-f515235ec727.png)

**Comment by akhilravuri1** [comment]
Okay.. the node version looks fine.

Now go to the output tab and select Db2Connect.

And paste the logs here.

**Comment by smithprasadgit** [comment]
[20/1/2021 3:57:54 pm] Proceeding to rebuild native modules
[20/1/2021 3:57:54 pm] No ibm_db found...
Running npm install in c:\Users\SmithPrasad\.vscode\extensions\ibm.db2connect-2.0.0...
npm
 WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm
 ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! 
enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR!
 enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!
     C:\Users\SmithPrasad\AppData\Roaming\npm-cache\_logs\2021-01-20T10_27_57_924Z-debug.log
[20/1/2021 3:57:57 pm] ibm_db installation failed with code: 1
Error: Failed to execute command "npm" with  arguments "install" return code 1

**Comment by smithprasadgit** [comment]
ibm_db is installed in node module

**Comment by akhilravuri1** [comment]
But the log says npm is unable to find the ibm_db file

**Comment by smithprasadgit** [comment]
I installed it using global command. do i need to install inside .vscode folder?

**Comment by akhilravuri1** [comment]
Yes...you need to install in .vscode/extensions/ibm-db2connet folder..
With npm install ibmdb -vscode

**Comment by smithprasadgit** [comment]
ok, let me do

**Comment by akhilravuri1** [comment]
But in that way..It doesn't work..because after npm install it does some other work.

**Comment by akhilravuri1** [comment]
I am just trying to analyze why it is not working...Is git installed in your system

**Comment by smithprasadgit** [comment]
yes, git is installed
after triggering the command i am getting this error
PS C:\Users\SmithPrasad\.vscode\extensions\ibm.db2connect-2.0.0> npm i ibm_db --vscode    
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno ENOENT
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/ibmdb/node-ibm_db.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\SmithPrasad\AppData\Roaming\npm-cache\_logs\2021-01-20T11_30_17_865Z-debug.log
PS C:\Users\SmithPrasad\.vscode\extensions\ibm.db2connect-2.0.0>

**Comment by akhilravuri1** [comment]
can you run git -v and paste the output

**Comment by smithprasadgit** [comment]
PS C:\Users\SmithPrasad\Desktop\Tusi Code\Management-portal\Management-portal> git --version
git version 2.29.1.windows.1

**Comment by akhilravuri1** [comment]
not in power shell..normal cmd.
If git -v is not working in cmd just add that path to your env PATH variable.

**Comment by smithprasadgit** [comment]
It is there in the path. if i do git -v i am getting 
C:\Users\SmithPrasad>git -v
unknown option: -v
usage: git [--version] [--help] [-C <path>] [-c <name>=<value>]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | -P | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

**Comment by smithprasadgit** [comment]
Strange, everything looks fine

**Comment by akhilravuri1** [comment]
Give me some time to reproduce this issue.
If possible please run git --version in the vscode terminal and paste the output.

**Comment by akhilravuri1** [comment]
Some times vscode doesn't load all the env's in the system.

**Comment by smithprasadgit** [comment]
![image](https://user-images.githubusercontent.com/47138984/105170538-151b9e00-5b43-11eb-8218-0f5ea120d3d7.png)

**Comment by akhilravuri1** [comment]
Why your ss shows PS in the terminal.

My vscode terminal opens normal one...
![image](https://user-images.githubusercontent.com/32290825/105170768-6f1c6380-5b43-11eb-84fd-21c764b03243.png)

**Comment by smithprasadgit** [comment]
Looks like ibm_db is installing now

**Comment by smithprasadgit** [comment]
its working now, after bin i didn't put"\" in path variable

**Comment by smithprasadgit** [comment]
yes, I have configured for one db, I can see now

**Comment by smithprasadgit** [comment]
Thank you very much for the help and debug. Much Appreciated

**Comment by akhilravuri1** [comment]
Not a problem.
Next time if possible please create a new issue where you can directly fill the node version, vscode version all the dependencies.

Thanks,
Akhil
