### ISSUE TITLE
Command 'Db2: Connect' resulted in an error (command 'extension.Db2Connect' not found)

### ISSUE THREAD

**Issue by gcmanriq** [ibmdb/vscode-extension#50]
- Platform: MacOs Monterey version 12.5
- vscode Version: 1.70.1
- Is node.js and npm installed: yes
- node.js and npm Version: nodejs v18.7.0 and npm: 8.15.0
- Take a screen shot of VScode(Help->About) information and paste it:
![image](https://user-images.githubusercontent.com/17751295/184998149-2f9a6e69-ada7-440a-9dcb-4cd315b5009d.png)

Steps to Reproduce:

1. Install extension 
2. Go to DB2 Connect and select Connect Option
3. Db2Connect Output:
```
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

/Users/xxxxxx/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/installer/clidriver
Extraction of build.zip completed successfully... 

Successfully renamed the Electron binary
Error: dlopen(/Users/xxxxxx/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/build/Release/odbc_bindings.node, 0x0001): Library not loaded: '/Users/bjha/nodework/clidriver/lib/libdb2.dylib'
  Referenced from: '/Users/xxxxxx/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/build/Release/odbc_bindings.node'
  Reason: tried: '/Users/bjha/nodework/clidriver/lib/libdb2.dylib' (no such file), '/usr/lib/libdb2.dylib' (no such file)
```

Tried to unistall extension and restarted visual studio code several times and still the same issue.
Library is available under  /Users/xxxxxx/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/installer/clidriver/lib/libdb2.dylib but I can't create symbolic link in /usr/lib

**Comment by BjarniThor** [comment]
Having the exact same problem, looking forward to hearing about a solution. 
Have tried few different versions of Node as well as older versions of VSCode.

**Comment by bimalkjha** [comment]
@BjarniThor @gcmanriq I have just pushed the fix of this issue. In your vscode, click on View -> Command Palette -> Db2: Rebuild Native Module and issue should get fixed. Please try and update. Thanks.

**Comment by BjarniThor** [comment]
Very well done, confirmed working for me!
Thanks you.

**Comment by gcmanriq** [comment]
It is working, thanks!
