### ISSUE TITLE
Extension Broken (AGAIN) By VS Code Update

### ISSUE THREAD

**Issue by scotdb** [ibmdb/vscode-extension#51]
Once again (I've lost count of how many times this has happened) a VS Code update has broken Db2 Connect.

It's the usual symptoms -

Successfully renamed the directory.
Using the existing CLI Driver
/home/db2inst1/sqllib
Extraction of build.zip completed successfully... 

Error: ENOENT: no such file or directory, rename '/home/philip/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/build/Release/odbc_bindings_linux_19.node' -> '/home/philip/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/build/Release/odbc_bindings.node'

Of course, there is no file of that name in the build.zip file (only up to _18) : I assume this relates to Electron 19.   The current Electron appears to be 20 as far as I can see, so 19 isn't even "bleeding edge".

I'm using an existing Db2 install, because I was told previously that this would help to prevent issues with the download.  If I try to download I also get errors (with the download appearing to terminate part way through, and the NaN issues I've seen in the past also appearing). 

This happens after I attempted to reinstall Db2 Connect to resolve the other error that appears frequently -

Error: The module ​'\\?\c:\Users\teamd\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\build\Release\odbc_bindings.node’​
was compiled against a different Node.js version using​
NODE_MODULE_VERSION 103. This version of Node.js requires​
NODE_MODULE_VERSION 106. Please try re-compiling or re-installing​
the module (for instance, using `npm rebuild` or `npm install`).​

When are we going to get an extension that is robust.   Because it breaks so often our developers will not even consider moving away from Data Studio (unlike our z/OS developers who are virtually all now using the Db2 for z/OS Developer Extension).

**Comment by bimalkjha** [comment]
@scotdb @BjarniThor Just do `View -> Command Palette -> Db2: Rebuild Native Modules` and issue should be fixed. Thanks.

**Comment by scotdb** [comment]
It is, at least on the first of my boxes that I tried.

I see you've now added the binding files for Electron 19 and 20.

But why do we always have to report this before it is dealt with.  Surely you should be tracking new Electron releases and providing support for them before they arrive in the stable VS Code releases (after all VS Code previews are readily available to allow you to prepare for this).

**Comment by bimalkjha** [comment]
It is difficult to find which version of electron will be used in next release of vscode and when will be the next release unless it it out. Thanks.

**Comment by BjarniThor** [comment]
@bimalkjha well done, works for me. Thank you very much.
