### ISSUE TITLE
Db object filter functionality

### ISSUE THREAD

**Issue by stheub** [ibmdb/vscode-extension#52]
Hi,
Thank you very much for providing this very useful VS Code Extension.
We are missing some filter functionality for the Db2 objects (like Schemas, Tables, Stored Procedures, etc.) displayed in the tree view like it is known from IBM Data Studios's Db Explorer view.
The filter functionality is required because the number of db objects in the tree view could be really big (especially when connecting to Db2 for z/OS subsystems :-) ) and to be able to focus of some objects of interest the user needs to be able to filter the displayed objects on all levels by using some user supplied filter criteria like "object name starts with" (LIKE predicate on object name), etc..
Could this please be added?
Thank you very much in advance.
Best regards from Germany
Stefan

**Comment by bimalkjha** [comment]
Opened Epic https://jira.rocketsoftware.com/browse/DBC-12850 to implement this feature request. Thanks.

**Comment by bimalkjha** [comment]
@stheub Delivered code changes for Object Filter functionality and it will available with next release of db2connect extension.
For testing purpose, you can download https://github.com/ibmdb/vscode-extension/blob/master/db2connect-2.3.1.vsix and `install from VSIX` file.
Latest released version of db2connect extension is v2.3.1 on Marketplace which do not has this feature yet. It will be available in next release. Thanks.
