### ISSUE TITLE
Db2 extension not available for M1 processors

### ISSUE THREAD

**Issue by yuribreion1** [ibmdb/vscode-extension#53]
First, thank you for supporting this useful extension on VSCode. 

Switching my workstation to Mac OS M1, the extension is no longer available for usage, maybe due to the different architecture. 

- Platform: darwin arm64
- vscode Version:
- Is node.js and npm installed: yes
- node.js and npm Version: v16.14.2

```
NaN% | 8869756 bytes downloaded out of NaN bytes.
Downloading and extraction of node ibm_db Driver completed successfully... 

Successfully renamed the directory.
platform = darwin, arch = arm64, node.js version = v16.14.2
Mac OS 32 bit not supported. Please use an x64 architecture.
```

**Comment by bimalkjha** [comment]
@yuribreion1 The arm64 architecture is not supported by db2connect extension. An idea for this support is opened against IBM: https://ibm-data-and-ai.ideas.ibm.com/ideas/DB2CON-I-92 . You can upvote or add comment their.

But, we have workaround for it. If you install `Intel Chip` version of vscode on your Mac OS M1 system, you can install db2connect extension and it would work without any issue. Thanks.

**Comment by netskink** [comment]
Trying to run from intel did not work for me.  See my comments below https://ibmzxplore.influitive.com/forum/t/db2-connection-not-working/629/12
