### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by BenS-ao** [ibmdb/vscode-extension#56]
Not sure if this is the right place to go with this or not; the notifcation error was a bit vague. The error I got was `Failed to rebuild native modules, please reach out to our git page for help` when trying to install the Db2 Connect extension. This error is repeated everytime I try to access the extension after opening vscode. The Db2Connect Output readout is as follows:

`Intellisense Activated
[1/13/2023 9:05:07 AM] Proceeding to rebuild native modules
[1/13/2023 9:05:07 AM] No ibm_db found...
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip...

[0G
10.98% | 1083 bytes downloaded out of 9861 bytes.
Error [ERR_SOCKET_CLOSED]: Socket is closed
Error: aborted`

I'm not sure exactly what is happening. It appears to start downloading the file and then abort. The progress percentage also appears to vary (I have seen it up to 38%). I am not sure if something is blocked somewhere in the background, but I am able to manually access the website indicated in the output and download the file. If I can simply place that file in a specific directory for the extension to see and utilze, that might be all I need.
On a side note, I have been able to install and use the IBM Db2 for z/OS Developer Extension (any many other various vscode extensions) with out any issue. Any help or advice would be greatly appreciated.

- Platform: Windows 10
- vscode Version: 1.74.3
- Is node.js and npm installed: yes
- node.js and npm Version: node 16.16.0; npm 8.11.0
- 
![image](https://user-images.githubusercontent.com/115298838/212342088-52ea004e-2d13-488f-87a2-2d5bf9a442c0.png)
(the node version provided above was obtained by `node -v` in the command line)

**Comment by bimalkjha** [comment]
@BenS-ao It seems some issue with your proxy settings which prevents download of master.zip from github.com. Please check. 
If still do not work, then close vscode and open windows command prompt, cd to `C:\Users\USERID\.vscode\extensions\ibm.db2connect-2.3.0` directory and run `npm install ibm_db@latest` command. Then create an empty file `rebuilt_dont_delete` without any extension, under `C:\Users\USERID\.vscode\extensions\ibm.db2connect-2.3.0` directory. If file exists, then no action required. After that open vscode and try to use db2connect extension. Thanks.

**Comment by bimalkjha** [comment]
@BenS-ao Also you can try to fix the download issue by installing extension `win-ca`. Installing this extension has fixed similar issue #55. Thanks.

**Comment by BenS-ao** [comment]
> 

The npm install resolution worked for me (although it did complain about a few dependeny vulnerabilities). Thanks for the help.

Should the extension be updated, would I have to rerun the npm install, or would updates not be an issue?

**Comment by bimalkjha** [comment]
@BenS-ao Once VSCode updates the major version of electron, then again you have to run npm install. Current electron version used by vscode is 19.1.8. So, next install needed if electron version changes to 20 or later by vscode update. If major version of electron is not changed by vscode update, then no need to run npm install ibm_db. Thanks.
