### ISSUE TITLE
Rebuild Native Modules - Error: libdb2.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by DavidHappelIP** [ibmdb/vscode-extension#57]
- Platform: Manjaro Linux
- vscode Version: 1.74.3
- Is node.js and npm installed: yes
- node.js and npm Version: Node: 16.14.2  NPM: 6.13.4
- Take a screen shot of VScode(Help->About) information and paste it:
![image](https://user-images.githubusercontent.com/118831515/212877868-48a453f2-31ce-4b30-9cb5-8785a2f9de2d.png)

Steps to Reproduce:
1. Run: DB2: Rebuild Native Modules OR Install Db2 connect extension and go to the Db2 connect tab.

Whenever I try to rebuild native modules, or install db2 connect the installation of ODBC cli fails.

Output: 
`
Proceeding to rebuild native modules
No ibm_db found...
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip...
...
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...

/home/david/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/installer/clidriver
Extraction of build.zip completed successfully... 

Successfully renamed the Electron binary
Error: libdb2.so.1: cannot open shared object file: No such file or directory
`

**Comment by bimalkjha** [comment]
@DavidHappelIP Run below commands from terminal after closing vscode extension:
```
cd /home/david/.vscode/extensions/ibm.db2connect-2.3.0/
npm install ibm_db
touch rebuilt_dont_delete
ls -l rebuilt_dont_delete
```
Now, reopen vscode extension and try connection with db2 server. If still facing issue, then please share the complete output of above commands. Thanks.

**Comment by bimalkjha** [comment]
@DavidHappelIP I hope issue is fixed for you. If not then let us know. Closing the issue as of now. Thanks.
