### ISSUE TITLE
 Failed to connect to ip address/location: No available keyring backend found on osx arm64

### ISSUE THREAD

**Issue by netskink** [ibmdb/vscode-extension#59]
# Failed to connect to ip address/location: No available keyring backend found on osx arm64

## Platform Info

- Platform: osx arm64 
- vscode Version: 
```
Version: 1.75.0 (Universal)
Commit: e2816fe719a4026ffa1ee0189dc89bdfdbafb164
Date: 2023-02-01T15:24:42.903Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Darwin arm64 22.2.0
Sandboxed: No
```
- Is node.js and npm installed: yes
- node.js and npm Version:
```
$ node --version
v18.12.1
$ nom --version
9.3.1
```

Interesting the versions at the terminal are different from what is reported by viscode.?.?.!

- Take a screen shot of VScode(Help->About) information and paste it:
This is how I generated the above info.

## Steps to Reproduce:

1. Download openjdk tar file from openjdk.org
2. unpack tar file
3. copy jdk dir to `/Library/Java/JavaVirtualMachines/` this creates a `/Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk` with a `/Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk/Contents/Home/bin/java` vm.  Interesting is that even though I have another jvm setup, this setup on osx automatically picks the new java jvm. eg:
```
$  /Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk/Contents/Home/bin/java --version
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
$ which java
/usr/bin/java
$  /usr/bin/java --version
openjdk 19.0.2 2023-01-17
OpenJDK Runtime Environment (build 19.0.2+7-44)
OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)
```
4. Install extension
5. Modify extension `@ext:IBM.db2forzosdeveloperextension` > `JAVA:Home` to be `/Library/Java/JavaVirtualMachines/jdk-19.0.2.jdk/Contents/Home`
6. setup a connection according to procedure documented [here](https://ibmzxplore.influitive.com/forum/t/db2-connection-not-working/629/10): 
7. click connection chain icon. 

## Result:
```
Failed to connect to 204.90.115.200/DALLASC: No available keyring backend found

Source: IBM Db2 for z/OS Developer Extension (Extension)
```

**Comment by netskink** [comment]
I tried another approach.

I made a dir in my home directory named `savethis`.  I used finder to move the `/Applications/Visual Studio Code` icon to `~/savethis`.  Essentially uninstalling my original arm version of vscode.

I then used finder to launch the intel version of vscode in `~/Downloads`.  It runs with the same extensions as before and looks like my previous installation of vscode.  However, it runs much slower.  Much, much slower.

I navigated to the DB2 Developer Extension and attempted to connect to `204.90.115.200/Dallasc` and got the same error as before.

Perhaps I need to move my ~/.vscode dir to remove my extensions.  I'll try that.

**Comment by netskink** [comment]
Hmm.  I closed the intel version of vscode.   I moved my `~/.vscode` dir to `~/savethis`.  I started the intel version again.  It did not have any extensions installed.

I installed the `IBM Db2 developer extension for z/OS`.  Oddly it already had my settings preserved from the previous install.  The setting for JDK was already present.  The Db2 for z/OS connection with `204.90.115.200/DALLASC` was present.  Attempting to connect to the host resulted in the same error.  `Failed to connect ...:No available keyring`

**Comment by netskink** [comment]
Hmm. I am trying to find your extension in vscode.  I searched for "IBM Db2 Connect" and the first one that pops up is "IBM Cloud Account".  Is yours in the vscode extension marketplace?


Do you know the GitHub for the "IBM Db2 for z/OS Developers"?

**Comment by netskink** [comment]
Ahh, I found it via "Db2 Connect"

**Comment by bimalkjha** [comment]
@netskink You need to search for "Db2Connect" to find this extension.
`IBM Db2 for z/OS Developers` is not open source and it can not be found on github. You need to contact IBM Support for it. Thanks.

**Comment by netskink** [comment]
Ahh, many thanks.  I appreciate your help.
