### ISSUE TITLE
Db2 Extension fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by baklarz** [ibmdb/vscode-extension#6]
After installing and refreshing/reloading the Db2 Connect extension, none of the commands work. For each command you will get a VS Code error of `command 'extension.Db2Connect' not found`. It doesn't matter which one command I try (profiles), you get a similar message.

The sequence of installation steps was: 
1. Install VS Code through the Ubuntu software page (rather than MS directly)
2. Install the Linux Db2 Connect extension
3. Refresh/reload VS
4. F1 -> Try anything and it fails - Also says to open an issue on Github.

Also reran the entire process using the MS download site for VS Code and repeated the steps above. Exactly the same results. The other message that is displayed is:
`Failed to rebuild native modules ...`

Are there other software components that are required to run this extension? No mention is made of CLI/ODBC/JDBC drivers (either they are buried in the extension or need to be installed).  

Thanks.

**Comment by akhilravuri1** [comment]
Hi @baklarz 
You need to have node js and npm installed in your system. 
Clidriver is downloaded by the extension so no need to have clidriver.

please install node js and npm. Before installing the extension, please delete the ibmdb extension folder in $USERPROFILE/.vscode/extensions.

Thanks,
Akhil

**Comment by baklarz** [comment]
Thanks for the information. Is it possible to update the Blog (https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/VSCode_Extension_for_DB2?lang=en), the Visual Studio Code library (https://marketplace.visualstudio.com/items?itemName=IBM.Db2Connect-linux), the installation notes (https://www.ibm.com/developerworks/community/blogs/96960515-2ea1-4391-8170-b0515d08e4da/entry/VS_Code_extension_for_Db2Connect?lang=en) as well as the Requirements section in the Visual Studio download to make sure that this highlighted as a requirement? The only way I would have known is with the Github readme for issues (which obviously I didn't read!). Want to make sure that you place the requirements in the VS Code section somewhere because I couldn't find these requirements until I raised the issue.

**Comment by baklarz** [comment]
After installing node.js and npm, I continue to have failures on the build. I created a Ubuntu 18.04LTS system from scratch and installed nodejs/npm (version 8.10/12/13 all tested) with Visual Studio Code (Ubuntu install and Microsoft deb install) and consistently get the installation error. Are there any log files produced by the installer that can be examined to find out why it is having issues creating the assets? If I do an npm ibm_db install it has no problem finding the packages etc... so at least I know it can complete that part.

**Comment by baklarz** [comment]
Sorry for all of the comments. I tried another approach. Installed npm/nodejs and then installed VS Code directly from the .deb image from Microsoft instead of using the Ubuntu software installer. That worked successfully. So somewhere there is a missing library or path or ... In any case, it would be good to know if there are any logs available that would help to pinpoint what was happening in these installs. 

Another interesting observation. I have the database locally on Ubuntu and if I use a connection profile, or a connection string, the connection will fail with SQL300031N Specific code 115 with a selectForConnectTimeout. I can successfully connect from a command line, from Jupyter notebooks using Python, and Go. So there was something going wrong with the Connection call. I'm using DATABASE=SAMPLE;HOST=localhost;PORT=50000;UID=DB2INST1;PWD=xxxxxx; which is all standard connection strings. It ends up that because we are communicating from nodejs to Db2 that we need to start ufw firewall with port 50000 to allow the nodejs service to talk to Db2. Another thing to mention in the documentation.

**Comment by akhilravuri1** [comment]
Hi @baklarz 
I have noted the points..we will update the documentation.

1) node.js and npm in the blog, marketplace.
2) start ufw firewall with port 50000 to allow the node.js service to talk to Db2.

Thanks,
Akhil

**Comment by pdbossman** [comment]
The port used for Db2 is a configurable parameter, so the instructions should indicate to open the port used by Db2.

**Comment by akhilravuri1** [comment]
> The port used for Db2 is a configurable parameter, so the instructions should indicate to open the port used by Db2, which by default is 50000.

It is the responsibility of the user to allow the node.js to use port number 50000.
