### ISSUE TITLE
Once again node.js version is too old on upgrading VS Code !!!

### ISSUE THREAD

**Issue by scotdb** [ibmdb/vscode-extension#60]
[10/05/2023 00:18:52] Native modules already rebuilt
Error: The module '/home/philip/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/build/Release/odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 106. This version of Node.js requires
NODE_MODULE_VERSION 110. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

**Comment by bimalkjha** [comment]
@scotdb please use Rebuld  Native Module option. Thanks.

**Comment by bimalkjha** [comment]
@scotdb Its similar to closed issue #51. Since, vscode has updated major version of electron, you need to use `View -> Command Palette -> Db2: Rebuild Native Modules` option and rebuild the module. It should fix this issue. Thanks.
