### ISSUE TITLE
VSCode Native modules: Failed to rebuild native modules, please reach out to our git page for help

### ISSUE THREAD

**Issue by TilenRupar** [ibmdb/vscode-extension#62]
- Platform:
- vscode Version: 1.78.2
- Screen shot of VScode(Help->About) information:
![image](https://github.com/ibmdb/vscode-extension/assets/85453602/cfdcc5ea-d57d-480e-b5e0-199a23af3c0c)

Steps to Reproduce:

1. Install extension
2. Bug is present when clicking on the icon on the left

Trying to rebuild Native Modules:
1. Command Pallete <- Db2: Rebuild Native Modules
2. Error: Failed to rebuild native modules, please reach out to our git page for help

**Comment by lgiammattei** [comment]
Same here

**Comment by bimalkjha** [comment]
@lgiammattei @TilenRupar Its similar to closed issue https://github.com/ibmdb/vscode-extension/issues/51. Since, vscode has updated major version of electron, you need to use `View -> Command Palette -> Db2: Rebuild Native Modules` option and rebuild the module. It should fix this issue. Let me know if issue still exists. Thanks.

**Comment by bimalkjha** [comment]
If still issue exists, then uninstall the extension and reinstall it. Thanks.

**Comment by TilenRupar** [comment]
Tried both, did not help.

**Comment by bimalkjha** [comment]
@TilenRupar Open VSCode, click on Extensions and search for "db2 connect". Click on uninstall button. Then close VSCode and cd to `C:\Users\$USER\.vscode\extensions` directory. Delete the folder `ibm.db2connect-2.3.0` manually. Now, open VSCode and reinstall db2connect extension. After installation, click on db2connect icon in the left bar and wait for the native module to be installed. You'll see a message for that. Once native module get installed successfully, you are ready to use the extension.
I verified these steps using VSCode V1.78.2 on Windows and it is working fine for me.

If still do not work then try below steps:
```
close vscode
cd dir C:\Users\%USERNAME%\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\build\Release
Check you have `odbc_bindings_win_22.node` file or not. If present, then delete existing `odbc_bindings.node` file
Rename `odbc_bindings_win_22.node` to `odbc_bindings.node`. 
Now, start vscode and use the db2connect extension. It should work.
```
If still do not work, then share the complete output of below commands from windows command prompt:
```
dir C:\Users\%USERNAME%\.vscode\extensions\ibm.db2connect-2.3.0\node_modules\ibm_db\build\Release
dir C:\Users\%USERNAME%\.vscode\extensions\ibm.db2connect-2.3.0\
```
Thanks.
