### ISSUE TITLE
Db2 Connect vscode extension fails to run

### ISSUE THREAD

**Issue by bbredenkamp** [ibmdb/vscode-extension#63]
- Platform: macOS: 13.5.2 (22G91)
- vscode Version:  1.82.2 (Universal)
- Is node.js and npm installed: yes and yes 
- node.js and npm Version:

node -e "console.log(process.versions)"
{
  node: '18.8.0',
  v8: '10.2.154.13-node.11',
  uv: '1.44.2',
  zlib: '1.2.11',
  brotli: '1.0.9',
  ares: '1.18.1',
  modules: '108',
  nghttp2: '1.49.0',
  napi: '8',
  llhttp: '6.0.7',
  openssl: '1.1.1q',
  cldr: '40.0',
  icu: '70.1',
  tz: '2021a3',
  unicode: '14.0'
}

npm --version
8.18.0

- Take a screen shot of VScode(Help->About) information and paste it:

<img width="1421" alt="image" src="https://github.com/ibmdb/vscode-extension/assets/20599519/66dddf91-0387-4d7c-8d85-852f06eb94eb">

Steps to Reproduce:

1. Install Db2 Connect Extension in vscode

Log Output: 

Intellisense Activated
[04/10/2023 09:14:05] Native modules already rebuilt
Error: The module '/Users/benb/.vscode/extensions/ibm.db2connect-2.3.0/node_modules/ibm_db/build/Release/odbc_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 110. This version of Node.js requires
NODE_MODULE_VERSION 116. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).

The extension was working until the other day.

**Comment by bimalkjha** [comment]
@bbredenkamp There is no change in the node.js version between vscode v1.82.0 and v1.82.2 i.e. NODE_MODULE_VERSION is unchanged. Can you close and reopen the vscode editor post installation of db2connect extension and check?
If still do not work, then you need to run below commands from terminal and reopen vscode:
cd /Users/benb/.vscode/extensions/ibm.db2connect-2.3.0/
npm install ibm_db

**Comment by bbredenkamp** [comment]
Good day! I was working on this in the meantime. The following looked like it worked, 
"
cd ~/.vscode/extensions/ibm.db2connect-2.3.0/node_modules
npm install
npm audit fix
"
but I will give package install a try and let you know the outcome.
