### ISSUE TITLE
Unable to load extendsion

### ISSUE THREAD

**Issue by ckxddd0324** [ibmdb/vscode-extension#65]
- Platform: iOS M2pro
- vscode Version:  1.85.1
- Is node.js and npm installed: yes/no yes
- node.js and npm Version: node - 18.18.0 and 9.8.1
- Take a screen shot of VScode(Help->About) information and paste it:

Steps to Reproduce:

1. Install intel version vscode
2. add license
3. Try to add connection parameter
4. error returns 
```bash
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

Log output
```bash
Intellisense Activated
[1/12/2024 12:41:43 PM] Native modules already rebuilt
```

**Comment by bimalkjha** [comment]
@ckxddd0324 iOS M2pro should have arm64 architecture. db2connect extension works only with x64 version of vscode. Please uninstall your existing vscode and install x64 version of vscode and then install db2connect extension. Share screenshot of vscode version info that captures all details. Thanks.
