### ISSUE TITLE
Can I connect to Db2 on Cloud?

### ISSUE THREAD

**Issue by lruffing** [ibmdb/vscode-extension#66]
- Platform: Windows 10
- vscode Version:
- Is node.js and npm installed: yes
- node.js and npm Version:
- Take a screen shot of VScode(Help->About) information and paste it:
- Version: 1.85.2 (user setup)
Commit: 8b3775030ed1a69b13e4f4c628c612102e30a681
Date: 2024-01-18T06:40:10.514Z
Electron: 25.9.7
ElectronBuildId: 26354273
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Supplied connection parameters to my Db2 on Cloud instance but it fails to connect with this error:
Connection to database failed: Error: [IBM][CLI Driver] SQL30081N A communication error has been detected. Communication protocol being used: "TCP/IP". Communication API being used: "SOCKETS". Location where the error was detected: "52.116.3.61". Communication function detecting the error: "recv". Protocol specific error code(s): "10054", "*", "0". SQLSTATE=08001

**Comment by bimalkjha** [comment]
@lruffing Yes, you can connect Db2 on Cloud using db2connect extension. You need to use correct database connection info. The TCPIP Error Code 10054 means Connection Refused by Server. So, either you are using wrong port number or wrong communication protocol.
How are you trying to create to Db2? Using direct connection string or by creating connection profile? If SSL is enabled on server, then check SSL Connection box while creating profile.
You can share more info with screenshot here about how are you trying connection. If using connection string, then share the connection string here by changing the sensitive info. Thanks.

**Comment by lruffing** [comment]
> @lruffing Yes, you can connect Db2 on Cloud using db2connect extension. You need to use correct database connection info. The TCPIP Error Code 10054 means Connection Refused by Server. So, either you are using wrong port number or wrong communication protocol. How are you trying to create to Db2? Using direct connection string or by creating connection profile? If SSL is enabled on server, then check SSL Connection box while creating profile. You can share more info with screenshot here about how are you trying connection. If using connection string, then share the connection string here by changing the sensitive info. Thanks.

Thank you! I needed to check the SSL box and now I can connect.

**Comment by lruffing** [comment]
Issue resolved by selecting the SSL checkbox for the connection.
