### ISSUE TITLE
Unable to run SP with NULL parameter

### ISSUE THREAD

**Issue by dangeville-n** [ibmdb/vscode-extension#67]
I'm trying to drop a schema and all of the tables using this command:

CALL SYSPROC.ADMIN_DROP_SCHEMA('EZSCH', NULL, ERRORSCHEMA, ERRORTABLE);

it does not delete anything And when I run the file it says

CALL SYSPROC.ADMIN_DROP_SCHEMA ( ?, ?, ?, ? )

Number of Rows returned: 1

it's with Db2 in IBM cloud. When I do the same thing in the SQL console it works.

Is there a different syntax to call this stored procedure ?

**Comment by dangeville-n** [comment]
I tried to run it explicitly through a right click. But it does not let me enter NULL as a value.

**Comment by bimalkjha** [comment]
@dangeville-n Use `null` instead of NULL. Thanks.

**Comment by dangeville-n** [comment]
@bimalkjha it did not work.
Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0443N Routine "ADMIN_DROP_SCHEMA" (specific name "*P_SCHEMA") has returned an error SQLSTATE with diagnostic text "Invalid value specified for MODE parameter". SQLSTATE=38000

**Comment by bimalkjha** [comment]
@dangeville-n I am able to reproduce the issue and will deliver fix soon. Issue is not with SP execution but issue is specific to the NULL parameter. For non-null parameters, stored procedures are running fine. Thanks.

**Comment by bimalkjha** [comment]
Pushed below change in file `src/controllers/mainController.js` to fix this issue:
![image](https://github.com/ibmdb/vscode-extension/assets/11818648/8712bd13-b9b1-407e-a721-38959d5b7730)

This fix will be available as part of next release of db2connect extension. Thanks.
