### ISSUE TITLE
Extension crashes VS Code when trying to select rows in a table with a blob

### ISSUE THREAD

**Issue by dangeville-n** [ibmdb/vscode-extension#69]
I have a table with a BLOB
Extension crashes when I try to visualize the content of the table. 
I have captured the steps
![image](https://github.com/ibmdb/vscode-extension/assets/51311950/d0ae45a1-ff92-4e50-bdbe-42f21ee56dee)

![image](https://github.com/ibmdb/vscode-extension/assets/51311950/7391b783-d7e8-4443-b58d-2841775f91fc)

![image](https://github.com/ibmdb/vscode-extension/assets/51311950/e51c6182-bb2e-434c-85c0-5136ac04790f)

I have multiple pop ups and the VS code resets as if restarting.

**Comment by bimalkjha** [comment]
@dangeville-n I see the error is from the extension ibm.zopeneditor-3.4.0 and not from db2connect extension. I think you are using this extension: https://marketplace.visualstudio.com/items?itemName=IBM.zopeneditor
So, this issue does not seem a db2connect extension issue and you should report this issue at https://github.com/IBM/zopeneditor-about/issues . Thanks.
