### ISSUE TITLE
Db2 connection commands failed.

### ISSUE THREAD

**Issue by bisop1985** [ibmdb/vscode-extension#7]
I can't connect to db2 servers with this extension.
Error message is:
command 'extension.Db2ManageConnProfiles' not found
I had several times reinstall. Node.js and Npm is already installed.
What can i do?

**Comment by akhilravuri1** [comment]
Hi @bisop1985 

can you please tell us which platform are you using and the vscode version?

Thanks,
Akhil

**Comment by bisop1985** [comment]
Hi Akhil,

i use on windows and the vscode version is: 1.41.1

**Comment by akhilravuri1** [comment]
Hi @bisop1985 

please uninstall the extension and go C:\Users\uname\.vscode\extensions and delete the Db2Connect folder and try to install it again.

Thanks,
Akhil

**Comment by bisop1985** [comment]
I did and now i have 2 error messages:
Failed to rebuild native modules, please reach out to our git page...
command 'extension.Db2ManageConnProfiles' not found

**Comment by akhilravuri1** [comment]
Hi @bisop1985 

Have you deleted "ibm.db2connect-win-1.1.0" this folder?

Thanks,
Akhil

**Comment by bisop1985** [comment]
Yepp

**Comment by akhilravuri1** [comment]
Please follow the steps:-

1) uninstall the extension.
2)CD to .vscode/extensions folder and delete the "ibm.db2connect-win-1.1.0"
3) Install the extension.
4) In command palette  search for DB2 and click any option then you will see a notification like this.
![Screenshot (87)](https://user-images.githubusercontent.com/32290825/72704939-1442db80-3b80-11ea-9b82-611cb8a57017.png)

5) After the installation, you will see this message.
![Screenshot (88)](https://user-images.githubusercontent.com/32290825/72704984-38062180-3b80-11ea-894d-56eed0346b8d.png)


Can you please take a screenshot of these states and paste it?

Thanks,
Akhil

**Comment by bisop1985** [comment]
![image](https://user-images.githubusercontent.com/60004479/72705216-324a1500-3b5b-11ea-8b9d-a009d2065e44.png)

![image](https://user-images.githubusercontent.com/60004479/72705274-56a5f180-3b5b-11ea-9996-bf098613802d.png)

![image](https://user-images.githubusercontent.com/60004479/72705300-67eefe00-3b5b-11ea-806a-17071e111a21.png)

![image](https://user-images.githubusercontent.com/60004479/72705327-7806dd80-3b5b-11ea-8d36-4df48c780564.png)

![image](https://user-images.githubusercontent.com/60004479/72705341-8654f980-3b5b-11ea-956c-f661dba46fd7.png)

After the reinstall i have the same problem.

**Comment by akhilravuri1** [comment]
After installation are you deleting the folder or before installation?

Thanks,
Akhil

**Comment by bisop1985** [comment]
Before installation,
this is the folder now:
![image](https://user-images.githubusercontent.com/60004479/72705604-2f035900-3b5c-11ea-93cf-6559d9dcf4d7.png)

**Comment by akhilravuri1** [comment]
This is very strange I am also using windows 10 and I was able to install.

Please go to the vscode terminal and try to get the logs.

**Comment by akhilravuri1** [comment]
while installing go to OUTPUT tab in the terminal and select Db2Connect extension in that and copy-paste the log

**Comment by akhilravuri1** [comment]
![Screenshot (1)](https://user-images.githubusercontent.com/32290825/72706179-60dbe600-3b83-11ea-90ae-fde1977ffb2c.png)

**Comment by bisop1985** [comment]
the output tab is blank

**Comment by akhilravuri1** [comment]
You have to capture the output while installing the extension.

**Comment by bisop1985** [comment]
![image](https://user-images.githubusercontent.com/60004479/72707946-f1a1ca00-3b61-11ea-94c1-61f4118ba132.png)

**Comment by akhilravuri1** [comment]
click on extensions and select Db2Connect.

Like this:-
![image](https://user-images.githubusercontent.com/32290825/72713895-d51e8580-3b93-11ea-93a9-9a963ad9e8d8.png)

paste the log in the output:-
![image](https://user-images.githubusercontent.com/32290825/72713992-f97a6200-3b93-11ea-8377-9e05f2c0f7a7.png)


Thanks,
Akhil

**Comment by bisop1985** [comment]
![image](https://user-images.githubusercontent.com/60004479/72714243-b22daa80-3b6e-11ea-93a9-4273cf4fa4e5.png)

**Comment by akhilravuri1** [comment]
when after installation when you click any command for the first time Db2Connect option will be added after that it will the disabled.

**Comment by bisop1985** [comment]
always blank

**Comment by bisop1985** [comment]
[2020. 01. 20. 10:26:25] Proceeding to rebuild native modules
[2020. 01. 20. 10:26:25] No ibm_db found...
Running npm install,ibm_db in c:\Users\l.bihari\.vscode\extensions\ibm.db2connect-win-1.1.0...
'npm' is not recognized as an internal or external command,
operable program or batch file.
[2020. 01. 20. 10:26:25] ibm_db installation failed with code: 1
Error: Failed to execute command "npm" with  arguments "install, ibm_db" return code 1

**Comment by akhilravuri1** [comment]
npm is not recognized means npm is not installed.
please check node -v and npm -v working or not.

If working,
restart the vscode (I mean colse and open the vscode) or restart the system.

If not working,
Add node/bin to your path variable.
If possible paste your echo %PATH%  output.
after adding close and open the vscode.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Hi @bisop1985 
Is it working for you?

Thanks,
AKhil

**Comment by bisop1985** [comment]
No, but i give up. I found other way.

**Comment by akhilravuri1** [comment]
Okay...Thanks for letting us know. I will close this issue.

If possible please share the steps you used to solve this issue. This might help other users also.

Thanks,
Akhil

**Comment by akhilravuri1** [comment]
Were you able to install the driver?

or you have already installed the extension and suggesting to us that running SQl queries can be made easier?

Thanks,
Akhil

**Comment by bisop1985** [comment]
I used an another way. I created a windows forms application. I give an Sql command as string and i become the result on datagridview.
