### ISSUE TITLE
Unable to install db2 connect extension

### ISSUE THREAD

**Issue by ayvamit** [ibmdb/vscode-extension#72]
Installation stuck after log 
ODBC Driver path = /Users/username/.vscode/extensions/ibm.db2connect-2.3.1/node_modules/ibm_db/installer/clidriver

I have also tried to run below command but still same issue. Once I open vscode it will again start to download and install.
```
cd c:\Users\USER.vscode\extensions\ibm.db2connect-2.3.1\node_modules\ibm_db
npm install --vscode
cd c:\Users\USER.vscode\extensions\ibm.db2connect-2.3.1
echo "" > rebuilt_dont_delete
```

- Platform: Mac OS x64
- vscode Version: 1.88.0
- Is node.js and npm installed: yes
- node.js and npm Version: node js : v18.17.1 npm version9.6.7
- Take a screen shot of VScode(Help->About) information and paste it:
```
Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.4.0
```

Steps to Reproduce:

1. Install Db2 Connect
2. Select Db2 Connect icon from sidebar

Following logs 
```
Intellisense Activated
[4/9/2024 5:12:08 PM] Proceeding to rebuild native modules
Error: ENOENT: no such file or directory, access '/Users/amityadav/.vscode/extensions/ibm.db2connect-2.3.1/node_modules/ibm_db'
[4/9/2024 5:12:08 PM] No ibm_db found...
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip ...
Downloading and extraction of node ibm_db Driver completed successfully.
Downloading took 2.8 seconds.
Successfully renamed the directory.
platform = darwin, arch = x64, node.js version = v18.18.2
Electron Version = 28.2.8
Downloading DB2 ODBC/CLI Driver ...
0.01% | 1378 bytes downloaded out of 21587031 in 1.9 seconds.
10.03% | 2165506 bytes downloaded out of 21587031 in 2.1 seconds.
20.05% | 4328194 bytes downloaded out of 21587031 in 2.3 seconds.
30.07% | 6490882 bytes downloaded out of 21587031 in 2.5 seconds.
40.01% | 8637186 bytes downloaded out of 21587031 in 2.6 seconds.
50.03% | 10799874 bytes downloaded out of 21587031 in 2.8 seconds.
60.05% | 12962562 bytes downloaded out of 21587031 in 3 seconds.
70.07% | 15125250 bytes downloaded out of 21587031 in 3.2 seconds.
80.01% | 17271554 bytes downloaded out of 21587031 in 3.4 seconds.
90.03% | 19434242 bytes downloaded out of 21587031 in 3.6 seconds.
100.00% | 21587031 bytes downloaded out of 21587031 in 3.8 seconds.
Downloading took 3.8 seconds.
Downloading and extraction of DB2 ODBC CLI Driver completed successfully ...
ODBC Driver path = /Users/amityadav/.vscode/extensions/ibm.db2connect-2.3.1/node_modules/ibm_db/installer/clidriver

```

**Comment by ayvamit** [comment]
<img width="1321" alt="image" src="https://github.com/ibmdb/vscode-extension/assets/18839793/4a56cbba-c5b2-46ff-9544-1de663760c6d">

**Comment by bimalkjha** [comment]
@ayvamit Please share complete output of command `npm install --vscode` that you executed.
Also, it seems you have installed node 18.17.1 but vscode 1.88.0 started using node 18.18.2, so better to use this version of nodejs and then run `npm install --vscode`. If `npm install --vscode` succeeded, then starting vscode should not try to rebuild if it has installed for correct electron version. Thanks.

**Comment by ayvamit** [comment]
@bimalkjha 
Updated node js version to 18.18.2.
```
~/.vscode/extensions/ibm.db2connect-2.3.1/node_modules/ibm_db » node --version                                                                                                                                    amityadav@Amits-MacBook-Pro
v18.18.2
```

About Vs code
```
Version: 1.88.0 (Universal)
Commit: 5c3e652f63e798a5ac2f31ffd0d863669328dc4c
Date: 2024-04-03T13:28:18.899Z
Electron: 28.2.8
ElectronBuildId: 27744544
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Darwin x64 23.4.0
```
I have tried using setting clidriver as well following is output of `npm install --vscode` after setting clidriver path.

```
~/.vscode/extensions/ibm.db2connect-2.3.1/node_modules/ibm_db » npm install --vscode                                                                                                                              amityadav@Amits-MacBook-Pro

> ibm_db@3.2.4 install
> node installer/driverInstall.js

platform = darwin, arch = x64, node.js version = v18.18.2
make version =GNU Make 3.81

Proceeding to build IBM_DB for Electron framework...

Unable to detect electon installation.
Detected VSCode version1.88, will use Electron version 25.8.0

IBM_DB_HOME environment variable have already set to -> /Users/amityadav/db2/clidriver

Downloading of clidriver skipped - build is in progress...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  SOLINK_MODULE(target) Release/odbc_bindings.node

ibm_db installed successfully.

added 50 packages, and audited 51 packages in 15s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Opening vscode again installation starts 
```
Intellisense Activated
[4/10/2024 9:55:02 PM] Proceeding to rebuild native modules
[4/10/2024 9:55:02 PM] Cleaning up the current ibm_db
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip ...
Downloading and extraction of node ibm_db Driver completed successfully.
Downloading took 2.7 seconds.
Successfully renamed the directory.
Using the existing CLI Driver
ODBC Driver path = /Users/amityadav/db2/clidriver
```

<img width="1315" alt="image" src="https://github.com/ibmdb/vscode-extension/assets/18839793/e4137e31-0adb-491c-9e98-44c827f1bce5">

Again stuck here...
Its same with or without setting the IBM_DB_HOME

**Comment by bimalkjha** [comment]
@ayvamit Please use command `npm install -electron="28.2.8"` and not the `npm install -vscode`. In the shared output, we can see, ibm_db tried to use electron  25.8.0 and hence error. Thanks.

**Comment by ayvamit** [comment]
@bimalkjha I have used the given command but still same. Again rebuilt is happening.

```
~/.vscode/extensions/ibm.db2connect-2.3.1/node_modules/ibm_db » npm install -electron="28.2.8"                                                               amityadav@Amits-MacBook-Pro

> ibm_db@3.2.4 install
> node installer/driverInstall.js

platform = darwin, arch = x64, node.js version = v18.18.2
make version =GNU Make 3.81

Proceeding to build IBM_DB for Electron framework...

Found electron version, will use Electron version 28.2.8 to install ibm_db.

IBM_DB_HOME environment variable have already set to -> /Users/amityadav/db2/clidriver

Downloading of clidriver skipped - build is in progress...

  CXX(target) Release/obj.target/odbc_bindings/src/odbc.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_connection.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_statement.o
  CXX(target) Release/obj.target/odbc_bindings/src/odbc_result.o
  SOLINK_MODULE(target) Release/odbc_bindings.node

ibm_db installed successfully.

added 50 packages, and audited 51 packages in 10s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
Rebuilt native module is happening again and getting stuck.

Thanks

**Comment by bimalkjha** [comment]
@ayvamit Now, ibm_db is installed correctly. After this when you restart vscode and click on BEE icon, do you see the message that db2connect extension is trying to install native module again? It should not if your system has the file `~/.vscode/extensions/ibm.db2connect-2.3.1/rebuilt_dont_delete` that I think you have created before. Please check about existence of this file before starting VSCode. It it is missing, create it and then start vscode. Thanks.

**Comment by ayvamit** [comment]
@bimalkjha 
Yes again I see install native module.
I have file rebuilt_dont_delete
```
~/.vscode/extensions/ibm.db2connect-2.3.1 » ls                                                                                                               
CHANGELOG.md        README.md           extension.js        node_modules        package.json        snippets            syntaxes
LICENSE.txt         Resources           languageServer      package-lock.json   rebuilt_dont_delete src

~/.vscode/extensions/ibm.db2connect-2.3.1 » cat rebuilt_dont_delete                                                                                         

```

Thanks

**Comment by scotdb** [comment]
Similar happened to me on two Linux boxes when I upgraded to VS Code 1.88.0 (and now 1.88.1).

The rebuild of the native modules pops up, but it hangs.

Intellisense Activated
[12/04/2024 19:58:26] Proceeding to rebuild native modules
[12/04/2024 19:58:26] Cleaning up the current ibm_db
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip ...
Downloading and extraction of node ibm_db Driver completed successfully.
Downloading took 10.8 seconds.
Successfully renamed the directory.
Using the existing CLI Driver
ODBC Driver path = /home/db2inst1/sqllib
[12/04/2024 19:58:49] Proceeding to rebuild native modules
[12/04/2024 19:58:49] Cleaning up the current ibm_db
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip ...
Downloading and extraction of node ibm_db Driver completed successfully.
Downloading took 4.1 seconds.
Successfully renamed the directory.
Using the existing CLI Driver
ODBC Driver path = /home/db2inst1/sqllib

That's as far as it gets while hanging.

**Comment by bimalkjha** [comment]
@ayvamit I am able to reproduce the hang. It is happening due to a regression in dependent nodejs package `adm-zip`: https://github.com/cthackers/adm-zip/issues/475
I have pushed a temporary fix for db2connect extension in ibm_db package until fix for adm-zip issue does not get merged.
Please reopen VSCode and try to use db2connect extension. Issue should get fixed now.

@scotdb We have added support for electron 28 and 29 in ibm_db package. Please reopen vscode and try to use the db2connect extension. Native module should get updated correctly for new version of vscode.
Thanks.

**Comment by ayvamit** [comment]
@bimalkjha Issue still persists.

**Comment by bimalkjha** [comment]
@ayvamit Are you on IBM slack? If yes, ping bimal.jha1@ibm.com. Else, try to join https://rocketsoftware.webex.com/meet/bjha
Thanks.

**Comment by bimalkjha** [comment]
@ayvamit In my testing, it has fixed the issue. Try to uninstall and re-install db2connect extension. If still issue persists, probably we need a meeting where I can look your screen and try to find root cause. Send email to bimal.jha1@ibm.com if you want to schedule a meeting. Thanks.

**Comment by ayvamit** [comment]
@bimalkjha 
The issue resolved now
Thank you for connecting.

**Comment by bimalkjha** [comment]
@ayvamit Thanks for the confirmation. Closing the issue now.

**Comment by scotdb** [comment]
Seems fixed for me here as well.   I observed that I had to reinstall the extension in Linux, but the module rebuild worked fine on Windows without a reinstall.
