### ISSUE TITLE
Japanese characters are not displayed correctly

### ISSUE THREAD

**Issue by shigerutkg** [ibmdb/vscode-extension#75]
I'm using DB2 LUW 11.1. When I connect to Unicode database (code page 1208) and SELECT, Japanese characters are not displayed correctly.

**Comment by bimalkjha** [comment]
@shigerutkg You need to set system level environment variable `DB2CODEPAGE=1208` and then restart vscode. Thanks.

**Comment by shigerutkg** [comment]
Thanks, solved.
