### ISSUE TITLE
Rebuild Native Modules Hangs (AGAIN) (related to #73)

### ISSUE THREAD

**Issue by g0ldfinch** [ibmdb/vscode-extension#77]
- Platform: Windows 11
- vscode Version: 1.95.2 (user)
- Is node.js and npm installed: yes
- node.js and npm Version: 20.18.0 (node.js) and 9.2.0 (npm)
- Take a screen shot of VScode(Help->About) information and paste it:
![image](https://github.com/user-attachments/assets/a7640b37-386c-45e5-9714-1583e0979096)

Steps to Reproduce:

1. Install the extension.
2. Look at the endless race of the blue line in the _Please wait while we are setting up native modules..._ popup.
3. Try to rebuild the modules, and then look at the race of 2 blue lines:
![image](https://github.com/user-attachments/assets/30707bd7-546b-4014-9d52-72c66593c9ee)

Extension log has this:

> Intellisense Activated
[11/10/2024 10:52:20 PM] Proceeding to rebuild native modules
[11/10/2024 10:52:20 PM] Cleaning up the current ibm_db
Downloading node ibm_db Driver from https://github.com/ibmdb/node-ibm_db/archive/master.zip ...
Downloading and extraction of node ibm_db Driver completed successfully.
Downloading took 24.1 seconds.
Successfully renamed the directory.
platform = win32, arch = x64, node.js version = v20.18.0
Electron Version = 32.2.1
Downloading DB2 ODBC/CLI Driver ...
0.06% | 16384 bytes downloaded out of 26444862 in 3.4 seconds.
10.06% | 2660523 bytes downloaded out of 26444862 in 3.6 seconds.
20.04% | 5298347 bytes downloaded out of 26444862 in 3.9 seconds.
30.01% | 7936171 bytes downloaded out of 26444862 in 4.1 seconds.
40.05% | 10590379 bytes downloaded out of 26444862 in 4.4 seconds.
50.02% | 13228203 bytes downloaded out of 26444862 in 4.6 seconds.
60.06% | 15882411 bytes downloaded out of 26444862 in 4.9 seconds.
70.03% | 18520235 bytes downloaded out of 26444862 in 5.1 seconds.
80.01% | 21158059 bytes downloaded out of 26444862 in 5.4 seconds.
90.04% | 23812267 bytes downloaded out of 26444862 in 5.6 seconds.
100.00% | 26444862 bytes downloaded out of 26444862 in 5.8 seconds.
Downloading took 5.8 seconds.
Downloading and extraction of DB2 ODBC CLI Driver completed successfully... 
ODBC Driver path = c:\Users\...\.vscode\extensions\ibm.db2connect-2.3.1\node_modules\ibm_db\installer\clidriver

Issue #73 mentioned that at the time of the fix electron version was 30, so rebuild enabled support of versions 30 and 31. Mine is 32, unfortunately... Uninstalling/reinstalling the extension, obviously, didn't help, that's why i'm raising the issue. Could it be due to node.js update? And what to do in this case? Can i downgrade electron somehow?

**Comment by g0ldfinch** [comment]
OK, Extension page has the following info:
![image](https://github.com/user-attachments/assets/1a6f4cda-f810-4283-a4b5-2c97a1205159)
That is, the extension was updated a few days ago... that's, probably, where electron v.32 is coming from...

**Comment by g0ldfinch** [comment]
Hi @bimalkjha , i noticed you fixed bug #73  - i wonder if you are still available to fix this one... Or, if it's just a matter of rebuilding the native modules and repacking the extension, can this be done by users like me? (I've never assembled any extension, but with clear instructions i may be able to do that as electron is a javascript-based application.) Then i may even be able to support it in such cases as this (:

**Comment by bimalkjha** [comment]
@g0ldfinch I am looking into it and will update you soon. Thanks.

**Comment by bimalkjha** [comment]
@g0ldfinch We have pushed fix for this issue. Please reopen vscode and try. Thanks.

**Comment by g0ldfinch** [comment]
Thanks a lot, it worked.
